[Default]
opensvc-use-collector-api = false
opensvc-p12-certificate = "etc/opensvc/cluster-api/cluster-demo/signal18.p12"
opensvc-host = "10.8.0.15:1215"
opensvc-p12-secret = "36vf2cczf8rms8hh"

# include ="etc/opensvc/cluster-api/cluster-demo/cluster.d"
# log-heartbeat = true

log-file="/var/log/replication-manager/replication-manager.log"
http-bind-address = "0.0.0.0"

# The client VPN address
monitoring-address = "10.8.0.70"

prov-orchestrator = "opensvc"
prov-net-cni-cluster = "repman"
prov-orchestrator-cluster = "cloud18"
prov-docker-daemon-private=false
prov-net-cni = true

prov-db-agents = "s18-fr-1,s18-fr-2"
prov-db-service-type = "docker"
prov-db-disk-type = "volume"
prov-db-volume-data = "db"

prov-proxy-agents = "s18-fr-1,s18-fr-2"
prov-proxy-service-type = "docker"
prov-proxy-disk-type = "volume"
prov-proxy-volume-data = "tank"
include ="etc/opensvc/cluster-api/cluster-demo/yorick.d"
