[Default]
http-server = true
http-session-lifetime = 86400
http-refresh-interval = 4000
monitoring-save-config = false
api-https-bind = true
api-credentials = "admin:uteliqagzhyx"
include = "/srv/slapgrid/slappart10/srv/runner/instance/slappart0/etc/repman/cluster.d"
autorejoin =  true 
autoseed =  true 
autorejoin-logical-backup = true
db-servers-binary-path = "/srv/slapgrid/slappart10/srv//runner//shared/mariadb/56de580c35c9de920a80ce14a4d4c974/bin"
# Database list of hosts to ignore in election
#db-servers-ignored-hosts =
# Database hosts list to monitor, IP and port (optional), specified in the host:[port] format and separated by commas
monitoring-address = "10.0.151.118"
monitoring-wait-retry = 40
#haproxy = true
#haproxy-binary-path = "/srv/slapgrid/slappart10/srv//runner//shared/haproxy/ca4d50df12cee3bb55d441e82bbd0661/sbin/haproxy"
# HaProxy input bind address for read (default "0.0.0.0")
#haproxy-ip-read-bind =
# HaProxy input bind address for write (default "0.0.0.0")
#haproxy-ip-write-bind =
# HaProxy load balance read port to all nodes (default 3307)
#haproxy-read-port =
# HaProxy hosts (default "127.0.0.1")
#haproxy-servers =
# HaProxy statistics port (default 1988)
#haproxy-stat-port =
#HaProxy read-write port to leader (default 3306)
#haproxy-write-port =
# Use restic to archive and restore backups
backup = true
backup-restic = true
backup-restic-binary-path = "/srv/slapgrid/slappart10/srv/runner/software/f79da523f3a00998198b14ccd9481612/go.work/bin/restic"
backup-restic-aws = false
backup-restic-password = "uteliqagzhyx"
backup-mysqlclient-path = "/srv/slapgrid/slappart10/srv//runner//shared/mariadb/56de580c35c9de920a80ce14a4d4c974/bin/mysql"
backup-mysqlbinlog-path = "/srv/slapgrid/slappart10/srv//runner//shared/mariadb/56de580c35c9de920a80ce14a4d4c974/bin/mysqlbinlog"
backup-mysqldump-path = "/srv/slapgrid/slappart10/srv//runner//shared/mariadb/56de580c35c9de920a80ce14a4d4c974/bin/mysqldump"
# Mail configuration
# Alert email sender (default "mrm@localhost")
mail-from = "alain.takoudjou@nexedi.com"
# Alert email SMTP server address, in host:[port] format (default "localhost:25")
mail-smtp-addr = "mail.tiolive.com:25"
mail-smtp-password = ""
mail-smtp-user = ""
# Alert email recipients, separated by commas
mail-to = ""
prov-orchestrator = "slapos"
sysbench-binary-path = "/srv/slapgrid/slappart10/srv//runner//shared/sysbench/fdbf54f681541a66540bfab93c10b17b/bin/sysbench"
# Number of threads to run benchmark (default 4)
sysbench-threads = 4
# Time to run benchmark (default 100)
sysbench-time = 100
sysbench-v1 = true



[cluster1]
title = "cluster1"
monitoring-save-config = true
db-servers-hosts = "[2001:67c:1254:e:89::5df3]:2099,[2001:67c:1254:e:89::5df3]:2199"
db-servers-prefered-master = "[2001:67c:1254:e:89::5df3]:2099"
db-servers-credential = "repman:ztocldvkbmqp"
replication-credential = "repman:ztocldvkbmqp"
monitoring-write-heartbeat-credential="heartbeat:ztocldvkbmqp"
db-servers-connect-timeout = 1
slapos-db-partitions = "/srv/slapgrid/slappart10/srv/runner/instance/slappart1,/srv/slapgrid/slappart10/srv/runner/instance/slappart2"
shardproxy = true
slapos-shardproxy-partitions = "/srv/slapgrid/slappart10/srv/runner/instance/slappart3"
shardproxy-servers-ipv6 = "[2001:67c:1254:e:89::5df3]"
shardproxy-copy-grants =  true 
shardproxy-credential =  "external:djpkcwaronlu"
shardproxy-load-system =  true 
shardproxy-servers = "10.0.151.118:6032"
shardproxy-universal-tables = "replication_manager_schema.bench"
prov-db-tags = "gtidstrict,bind,pkg,innodb,noquerycache,slow,pfs,linux,readonly,diskmonitor,sqlerror,compressbinlog,bm4ci,mroonga,utctime,readcommitted,nohandshake"
prov-proxy-tags = "pkg,masterslave,linux,noreadwritesplit"
monitoring-scheduler = true
scheduler-db-servers-logical-backup  = true
scheduler-db-servers-logical-backup-cron = "0 0 22 * * *"
scheduler-db-servers-logs   =  true
scheduler-db-servers-logs-cron = "0 0 23 * * *"
scheduler-db-servers-logs-table-keep = 4
scheduler-db-servers-logs-table-rotate  = true
scheduler-db-servers-logs-table-rotate-cron = "0 0 23 * * *"
scheduler-db-servers-optimize  = true
scheduler-db-servers-optimize-cron = "0 0 3 1 * 5"
scheduler-db-servers-physical-backup = true
scheduler-db-servers-physical-backup-cron = "0 0 0 * * *"
backup-physical-type = "mariabackup"
backup-logical-type = "mysqldump"
scheduler-db-servers-receiver-ports= "2108,2208"
prov-proxy-cpu-cores = 2
prov-proxy-memory = 1
prov-db-cpu-cores = 4
prov-db-disk-iops = 300
prov-db-memory = 2048
prov-db-memory-shared-pct = "threads:16,innodb:60,myisam:10,aria:10,rocksdb:1,tokudb:1,s3:1,archive:1,querycache:0"
prov-db-memory-threaded-pct = "tmp:70,join:20,sort:10"
test-inject-traffic = true
# failover
failover-mode = "manual"
failover-limit = 5
failover-falsepositive-heartbeat =  true 
failover-falsepositive-heartbeat-timeout = 3
failover-falsepositive-ping-counter = 5
failover-max-slave-delay = 30
failover-readonly-state =  true 
failover-restart-unsafe =  false 
failover-time-limit = 0
#switchover
switchover-at-equal-gtid =  false 
switchover-slave-wait-catch =  true 
switchover-wait-kill = 5000
switchover-wait-trx = 10
switchover-wait-write-query = 10
