
[yorick]
title = "yorick"
db-servers-hosts = "db1,db2"
db-servers-prefered-master = "db1"
db-servers-credential = "root:mariadb"
db-servers-connect-timeout = 1
replication-credential = "root:mariadb"
force-slave-readonly = true
prov-db-docker-img = "mariadb:10.5"
prov-db-tags = "docker,linux,innodb,noquerycache,threadpool,slow,ssd,localinfile,nodoublewrite,compressbinlog,noadaptiveflush,relayspacelimit,optimistic"
prov-db-disk-size = "2"
prov-db-memory = "256"
prov-db-disk-iops = "10000"
prov-db-cpu-cores = "8"
monitoring-scheduler = false
# backup-restic = true

proxysql=true
proxysql-port = 3306
proxysql-servers = "proxysql1,proxysql2"
proxysql-user ="external"
proxysql-bootstrap= true
proxysql-copy-grants = true
prov-proxy-disk-size = "1"
