{
 "title": "Connections",
 "panels": [
  {
   "title": "IO Thread Running",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql.$host.mysql_slave_status_slave_io_running"
    }
   ]
  },
  {
   "title": "SQL Thread Running",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql.$host.mysql_slave_status_slave_sql_running"
    }
   ]
  },
  {
   "title": "Replication Error No",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql.$host.mysql_slave_status_last_errno"
    }
   ]
  },
  {
   "title": "Read Only",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_read_only"
    }
   ]
  },
  {
   "title": "MySQL Replication Delay",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql.$host.mysql_slave_status_seconds_behind_master",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "title": "Binlogs Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql.$host.mysql_global_variables_max_binlog_size",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Binlog Data Written Hourly",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql.$host.mysql_global_status_binlog_bytes_written[1h])",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Binlogs Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "calculatedInterval": "2m", "expr": "mysql_binlog_files", "legendFormat": "Count" }
   ]
  },
  {
   "title": "Binlogs Created Hourly",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_binlog_file_number[1h])",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Relay Log Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql.$host.mysql_slave_status_relay_log_space",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Relay Log Written Hourly",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql.$host.mysql_slave_status_relay_log_space[1h])",
     "legendFormat": "Size"
    }
   ]
  }
 ]
}