// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: cluster.proto

package repmanv3

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_cluster_proto protoreflect.FileDescriptor

const file_cluster_proto_rawDesc = "" +
	"\n" +
	"\rcluster.proto\x12\x1fsignal18.replication_manager.v3\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x0emessages.proto2\xa5\x02\n" +
	"\x14ClusterPublicService\x12v\n" +
	"\rClusterStatus\x12(.signal18.replication_manager.v3.Cluster\x1a\x17.google.protobuf.Struct\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v3/clusters/{name}/status\x12\x94\x01\n" +
	"\x14MasterPhysicalBackup\x12(.signal18.replication_manager.v3.Cluster\x1a\x16.google.protobuf.Empty\":\x82\xd3\xe4\x93\x024\x122/v3/clusters/{name}/actions/master-physical-backup2\xc0\x0f\n" +
	"\x0eClusterService\x12l\n" +
	"\n" +
	"GetCluster\x12(.signal18.replication_manager.v3.Cluster\x1a\x17.google.protobuf.Struct\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v3/clusters/{name}\x12\x80\x01\n" +
	"\x15GetSettingsForCluster\x12(.signal18.replication_manager.v3.Cluster\x1a\x17.google.protobuf.Struct\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v3/clusters/{name}/settings\x12\x84\x03\n" +
	"\x1bSetActionForClusterSettings\x12/.signal18.replication_manager.v3.ClusterSetting\x1a\x16.google.protobuf.Empty\"\x9b\x02\x82\xd3\xe4\x93\x02\x94\x02ZC\x12A/v3/clusters/{cluster.name}/settings/actions/{action}/{tag_value}ZQ\x12O/v3/clusters/{cluster.name}/settings/actions/set/{setting.name}/{setting.value}ZC\x12A/v3/clusters/{cluster.name}/settings/actions/switch/{switch.name}\x125/v3/clusters/{cluster.name}/settings/actions/{action}\x12\xaf\x04\n" +
	"\x14PerformClusterAction\x12..signal18.replication_manager.v3.ClusterAction\x1a\x16.google.protobuf.Empty\"\xce\x03\x82\xd3\xe4\x93\x02\xc7\x03ZL\x12J/v3/clusters/{cluster.name}/actions/{action}/{cluster.clusterShardingName}ZJ\x12H/v3/clusters/{cluster.name}/actions/{action}/{server.host}/{server.port}ZX\x12V/v3/clusters/{cluster.name}/actions/{action}/{server.host}/{server.port}/{server.type}Z9\x127/v3/clusters/{cluster.name}/actions/{action}/{topology}Z.\x12,/v3/clusters/{cluster.name}/actions/{action}Z8:\x06server\"./v3/clusters/{cluster.name}/actions/switchover\x12,/v3/clusters/actions/{action}/{cluster.name}\x12\x9e\x01\n" +
	"\x14RetrieveFromTopology\x122.signal18.replication_manager.v3.TopologyRetrieval\x1a\x17.google.protobuf.Struct\"7\x82\xd3\xe4\x93\x021\x12//v3/clusters/{cluster.name}/topology/{retrieve}0\x01\x12\x84\x01\n" +
	"\x15GetClientCertificates\x12(.signal18.replication_manager.v3.Cluster\x1a\x17.google.protobuf.Struct\"(\x82\xd3\xe4\x93\x02\"\x12 /v3/clusters/{name}/certificates\x12v\n" +
	"\n" +
	"GetBackups\x12(.signal18.replication_manager.v3.Cluster\x1a\x17.google.protobuf.Struct\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v3/clusters/{name}/backups0\x01\x12p\n" +
	"\aGetTags\x12(.signal18.replication_manager.v3.Cluster\x1a\x17.google.protobuf.Struct\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v3/clusters/{name}/tags0\x01\x12|\n" +
	"\rGetQueryRules\x12(.signal18.replication_manager.v3.Cluster\x1a\x17.google.protobuf.Struct\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v3/clusters/{name}/queryrules0\x01\x12t\n" +
	"\tGetSchema\x12(.signal18.replication_manager.v3.Cluster\x1a\x17.google.protobuf.Struct\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v3/clusters/{name}/schema0\x01B2Z0github.com/signal18/replication-manager;repmanv3b\x06proto3"

var file_cluster_proto_goTypes = []any{
	(*Cluster)(nil),           // 0: signal18.replication_manager.v3.Cluster
	(*ClusterSetting)(nil),    // 1: signal18.replication_manager.v3.ClusterSetting
	(*ClusterAction)(nil),     // 2: signal18.replication_manager.v3.ClusterAction
	(*TopologyRetrieval)(nil), // 3: signal18.replication_manager.v3.TopologyRetrieval
	(*structpb.Struct)(nil),   // 4: google.protobuf.Struct
	(*emptypb.Empty)(nil),     // 5: google.protobuf.Empty
}
var file_cluster_proto_depIdxs = []int32{
	0,  // 0: signal18.replication_manager.v3.ClusterPublicService.ClusterStatus:input_type -> signal18.replication_manager.v3.Cluster
	0,  // 1: signal18.replication_manager.v3.ClusterPublicService.MasterPhysicalBackup:input_type -> signal18.replication_manager.v3.Cluster
	0,  // 2: signal18.replication_manager.v3.ClusterService.GetCluster:input_type -> signal18.replication_manager.v3.Cluster
	0,  // 3: signal18.replication_manager.v3.ClusterService.GetSettingsForCluster:input_type -> signal18.replication_manager.v3.Cluster
	1,  // 4: signal18.replication_manager.v3.ClusterService.SetActionForClusterSettings:input_type -> signal18.replication_manager.v3.ClusterSetting
	2,  // 5: signal18.replication_manager.v3.ClusterService.PerformClusterAction:input_type -> signal18.replication_manager.v3.ClusterAction
	3,  // 6: signal18.replication_manager.v3.ClusterService.RetrieveFromTopology:input_type -> signal18.replication_manager.v3.TopologyRetrieval
	0,  // 7: signal18.replication_manager.v3.ClusterService.GetClientCertificates:input_type -> signal18.replication_manager.v3.Cluster
	0,  // 8: signal18.replication_manager.v3.ClusterService.GetBackups:input_type -> signal18.replication_manager.v3.Cluster
	0,  // 9: signal18.replication_manager.v3.ClusterService.GetTags:input_type -> signal18.replication_manager.v3.Cluster
	0,  // 10: signal18.replication_manager.v3.ClusterService.GetQueryRules:input_type -> signal18.replication_manager.v3.Cluster
	0,  // 11: signal18.replication_manager.v3.ClusterService.GetSchema:input_type -> signal18.replication_manager.v3.Cluster
	4,  // 12: signal18.replication_manager.v3.ClusterPublicService.ClusterStatus:output_type -> google.protobuf.Struct
	5,  // 13: signal18.replication_manager.v3.ClusterPublicService.MasterPhysicalBackup:output_type -> google.protobuf.Empty
	4,  // 14: signal18.replication_manager.v3.ClusterService.GetCluster:output_type -> google.protobuf.Struct
	4,  // 15: signal18.replication_manager.v3.ClusterService.GetSettingsForCluster:output_type -> google.protobuf.Struct
	5,  // 16: signal18.replication_manager.v3.ClusterService.SetActionForClusterSettings:output_type -> google.protobuf.Empty
	5,  // 17: signal18.replication_manager.v3.ClusterService.PerformClusterAction:output_type -> google.protobuf.Empty
	4,  // 18: signal18.replication_manager.v3.ClusterService.RetrieveFromTopology:output_type -> google.protobuf.Struct
	4,  // 19: signal18.replication_manager.v3.ClusterService.GetClientCertificates:output_type -> google.protobuf.Struct
	4,  // 20: signal18.replication_manager.v3.ClusterService.GetBackups:output_type -> google.protobuf.Struct
	4,  // 21: signal18.replication_manager.v3.ClusterService.GetTags:output_type -> google.protobuf.Struct
	4,  // 22: signal18.replication_manager.v3.ClusterService.GetQueryRules:output_type -> google.protobuf.Struct
	4,  // 23: signal18.replication_manager.v3.ClusterService.GetSchema:output_type -> google.protobuf.Struct
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_cluster_proto_init() }
func file_cluster_proto_init() {
	if File_cluster_proto != nil {
		return
	}
	file_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_proto_rawDesc), len(file_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_cluster_proto_goTypes,
		DependencyIndexes: file_cluster_proto_depIdxs,
	}.Build()
	File_cluster_proto = out.File
	file_cluster_proto_goTypes = nil
	file_cluster_proto_depIdxs = nil
}
