FROM golang:1.24-trixie AS builder

RUN mkdir -p /go/src/github.com/signal18/replication-manager
WORKDIR /go/src/github.com/signal18/replication-manager

RUN apt-get update && apt-get -y install nodejs npm
COPY . .
RUN make osc cli
RUN go install github.com/moul/gotty-client/cmd/gotty-client@v1.10.0

FROM debian:trixie-slim

ENV PROXYSQL_VERSION=2.7.3
ENV MARIADB_VERSION=11.4
ENV MYDUMPER_VERSION=0.17.1-1

RUN mkdir -p \
        /etc/replication-manager \
        /etc/replication-manager/cluster.d \
        /var/lib/replication-manager \
        /var/lib/replication-manager/conf \
        /var/lib/replication-manager/recover

RUN apt-get update && apt-get -y  install apt-transport-https curl adduser \
 && mkdir -p /etc/apt/keyrings && curl -o /etc/apt/keyrings/mariadb-keyring.pgp 'https://mariadb.org/mariadb_release_signing_key.pgp'

COPY --from=builder /go/src/github.com/signal18/replication-manager/etc/local/config.toml.docker /etc/replication-manager/config.toml
COPY --from=builder /go/src/github.com/signal18/replication-manager/share /usr/share/replication-manager/
COPY --from=builder /go/src/github.com/signal18/replication-manager/build/binaries/replication-manager-osc /usr/bin/replication-manager
COPY --from=builder /go/src/github.com/signal18/replication-manager/build/binaries/replication-manager-cli /usr/bin/replication-manager-cli

RUN curl -LsS https://r.mariadb.com/downloads/mariadb_repo_setup | bash -s -- --mariadb-server-version="mariadb-$MARIADB_VERSION" --skip-maxscale
RUN groupadd -g 10001 repman \
  && useradd -r -u 10001 -g repman -d /var/lib/replication-manager -s /usr/sbin/nologin repman \
  && chown -R repman:repman /etc/replication-manager /etc/replication-manager/cluster.d /var/lib/replication-manager
USER repman
CMD ["replication-manager", "monitor", "--http-server"]
EXPOSE 10001
