FROM golang:1.20-bullseye

ENV PROXYSQL_VERSION=2.5.5

RUN mkdir -p /go/src/github.com/signal18/replication-manager
WORKDIR /go/src/github.com/signal18/replication-manager

COPY . .

RUN make pro cli

RUN mkdir -p \
        /etc/replication-manager \
        /etc/replication-manager/cluster.d \
        /var/lib/replication-manager


RUN cp etc/local/config.toml.docker /etc/replication-manager/config.toml && \
cp etc/local/masterslave/haproxy/config.toml /etc/replication-manager/cluster.d/localmasterslavehaproxy.toml && \
cp etc/local/masterslave/proxysql/config.toml /etc/replication-manager/cluster.d/localmasterslaveproxysql.toml && \
cp -r share /usr/share/replication-manager/ && \
cp build/binaries/replication-manager-pro /usr/bin/replication-manager && \
cp build/binaries/replication-manager-cli /usr/bin/replication-manager-cli

RUN apt-get update && apt-get -y install mydumper ca-certificates restic mariadb-client mariadb-server mariadb-plugin-spider haproxy libmariadb-dev fuse sysbench curl vim
RUN curl -LO https://github.com/sysown/proxysql/releases/download/v$PROXYSQL_VERSION/proxysql_$PROXYSQL_VERSION-debian11_amd64.deb && dpkg -i proxysql_$PROXYSQL_VERSION-debian11_amd64.deb
CMD ["while true ; do sleep 1; done"]
EXPOSE 10001
