FROM golang:1.25-bookworm AS builder

RUN mkdir -p /go/src/github.com/signal18/replication-manager
WORKDIR /go/src/github.com/signal18/replication-manager

RUN apt-get update && apt-get -y install curl ca-certificates && \
    curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
    apt-get install -y nodejs && \
    rm -rf /var/lib/apt/lists/*
COPY . .
ARG PLUGIN_SIGNER_USER=""
ARG PLUGIN_SIGNER_TOKEN=""
ARG PLUGIN_PUSH="OFF"
RUN make pro cli PLUGIN_SIGNER_USER="$PLUGIN_SIGNER_USER" PLUGIN_SIGNER_TOKEN="$PLUGIN_SIGNER_TOKEN" PLUGIN_PUSH="$PLUGIN_PUSH"
RUN go install github.com/moul/gotty-client/cmd/gotty-client@v1.10.0

FROM debian:bookworm-slim

ENV PROXYSQL_VERSION=2.7.3
ENV MARIADB_VERSION=11.4
ENV MYDUMPER_VERSION=0.17.1-1

RUN mkdir -p \
        /etc/replication-manager \
        /etc/replication-manager/cluster.d \
        /var/lib/replication-manager \
        /var/lib/replication-manager/conf \
        /var/lib/replication-manager/recover

RUN apt-get update && apt-get -y  install apt-transport-https curl \
 && mkdir -p /etc/apt/keyrings && curl -o /etc/apt/keyrings/mariadb-keyring.pgp 'https://mariadb.org/mariadb_release_signing_key.pgp'

COPY --from=builder /go/src/github.com/signal18/replication-manager/etc/local/config.toml.docker /etc/replication-manager/config.toml
COPY --from=builder /go/src/github.com/signal18/replication-manager/share /usr/share/replication-manager/
COPY --from=builder /go/src/github.com/signal18/replication-manager/build/binaries/replication-manager-pro /usr/bin/replication-manager
COPY --from=builder /go/src/github.com/signal18/replication-manager/build/binaries/replication-manager-cli /usr/bin/replication-manager-cli
COPY --from=builder /go/bin/gotty-client /usr/local/bin/gotty-client

RUN curl -LsS https://r.mariadb.com/downloads/mariadb_repo_setup | bash -s -- --mariadb-server-version="mariadb-$MARIADB_VERSION" --skip-maxscale
RUN apt-get update && apt-get -y install mydumper ca-certificates restic mariadb-client=1:11* mariadb-plugin-spider haproxy \
    libmariadb-dev fuse sysbench curl wget openssh-client libatomic1 libglib2.0 libpcre3 adduser libfontconfig1 \
  && curl -LO https://dl.grafana.com/oss/release/grafana_8.1.1_amd64.deb && dpkg -i grafana_8.1.1_amd64.deb && rm -f grafana_8.1.1_amd64.deb \
  && curl -LO https://github.com/sysown/proxysql/releases/download/v$PROXYSQL_VERSION/proxysql_$PROXYSQL_VERSION-debian12_amd64.deb && dpkg -i proxysql_$PROXYSQL_VERSION-debian12_amd64.deb \
  && curl -LO https://github.com/mydumper/mydumper/releases/download/v$MYDUMPER_VERSION/mydumper_$MYDUMPER_VERSION.bookworm_amd64.deb && dpkg -i mydumper_$MYDUMPER_VERSION.bookworm_amd64.deb \
  && rm -f *.deb && rm -rf /var/lib/mysql/*
COPY docker/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
COPY --from=builder /go/src/github.com/signal18/replication-manager/etc/local/config.toml.docker /usr/share/replication-manager/config.toml.default
RUN groupadd -g 10001 repman \
  && useradd -r -u 10001 -g repman -d /var/lib/replication-manager -s /usr/sbin/nologin repman \
  && chown -R repman:repman /etc/replication-manager /etc/replication-manager/cluster.d /var/lib/replication-manager \
  && chmod +x /usr/local/bin/docker-entrypoint.sh
USER repman
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["replication-manager", "monitor", "--http-server"]
EXPOSE 10001
