FROM golang:1.23-bookworm AS builder

ENV PROXYSQL_VERSION=2.5.5
# Using 0.17.1-1
ENV MARIADB_VERSION=11.4
ENV MYDUMPER_VERSION=0.17.1-1

RUN mkdir -p /go/src/github.com/signal18/replication-manager
WORKDIR /go/src/github.com/signal18/replication-manager

RUN curl -LsS https://r.mariadb.com/downloads/mariadb_repo_setup | bash -s -- --mariadb-server-version="mariadb-$MARIADB_VERSION"

# Move to top for better cache
RUN apt-get update && apt-get -y install ca-certificates restic mariadb-client mariadb-server mariadb-backup mariadb-plugin-spider haproxy libmariadb-dev fuse sysbench curl vim libatomic1 libglib2.0 libpcre3
RUN curl -LO https://github.com/sysown/proxysql/releases/download/v$PROXYSQL_VERSION/proxysql_$PROXYSQL_VERSION-debian11_amd64.deb && dpkg -i proxysql_$PROXYSQL_VERSION-debian11_amd64.deb
RUN curl -LO https://github.com/mydumper/mydumper/releases/download/v$MYDUMPER_VERSION/mydumper_$MYDUMPER_VERSION.bookworm_amd64.deb && dpkg -i mydumper_$MYDUMPER_VERSION.bookworm_amd64.deb

# Install Node.js 18 from NodeSource
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs && \
    rm -rf /var/lib/apt/lists/*

RUN /usr/local/go/bin/go install -v golang.org/x/tools/gopls@latest
RUN /usr/local/go/bin/go install -v github.com/cweill/gotests/gotests@v1.6.0
RUN /usr/local/go/bin/go install -v github.com/fatih/gomodifytags@v1.16.0
RUN /usr/local/go/bin/go install -v github.com/josharian/impl@v1.1.0
RUN /usr/local/go/bin/go install -v github.com/haya14busa/goplay/cmd/goplay@v1.0.0
RUN /usr/local/go/bin/go install -v github.com/haya14busa/goplay/cmd/goplay@v1.0.0
RUN /usr/local/go/bin/go install -v github.com/go-delve/delve/cmd/dlv@latest
RUN /usr/local/go/bin/go install -v honnef.co/go/tools/cmd/staticcheck@latest

COPY . .

RUN make pro cli && \
rm -f replication-manager-pro && \
rm -f replication-manager-cli && \
ln -s build/binaries/replication-manager-pro replication-manager-pro && \
ln -s build/binaries/replication-manager-cli replication-manager-cli

RUN mkdir -p \
        /etc/replication-manager \
        /etc/replication-manager/cluster.d \
        /var/lib/replication-manager


RUN cp etc/local/config.toml.docker /etc/replication-manager/config.toml && \
cp etc/local/masterslave/haproxy/config.toml /etc/replication-manager/cluster.d/localmasterslavehaproxy.toml && \
cp etc/local/masterslave/proxysql/config.toml /etc/replication-manager/cluster.d/localmasterslaveproxysql.toml && \
cp -r share /usr/share/replication-manager/ && \
cp build/binaries/replication-manager-pro /usr/bin/replication-manager && \
cp build/binaries/replication-manager-cli /usr/bin/replication-manager-cli

CMD ["while true; do sleep 86400; done"]
EXPOSE 10001
