package cluster

var clusterError = map[string]string{
	"ERR00005": "Could not get privileges for user %s@%s: %s",
	"ERR00006": "User must have REPLICATION CLIENT privilege",
	"ERR00007": "User must have REPLICATION SLAVE privilege",
	"ERR00008": "User must have SUPER privilege",
	"ERR00009": "User must have RELOAD privilege",
	"ERR00010": "Could not found a slave in topology",
	"ERR00011": "Found multiple masters in topology but not explicity setup",
	"ERR00012": "Could not found a master in topology",
	"ERR00013": "Binary log disabled on slave: %s",
	"ERR00014": "Could not get binlog dump count on server %s: %s",
	"ERR00015": "Could not get get privileges for user %s on server %s: %s",
	"ERR00016": "Master is unreachable but slaves are replicating",
	"ERR00017": "Unable to fetch MaxScale monitoring information",
	"ERR00018": "Could not connect to MaxScale: %s",
	"ERR00019": "Could not get MaxScale maxadmin server list: %s",
	"ERR00020": "Could not get MaxScale maxinfo server list: %s",
	"ERR00021": "All cluster down in non interactive mode",
	"ERR00022": "Running in passive mode",
	"ERR00023": "Constraint failed: state %s, conf.Interactive %t cluster.isMaxMasterFailedCountReach %t",
	"ERR00024": "Constraint failed: isExternalOk %t,isActiveArbitration %t,isBeetwenFailoverTimeTooShort %t ,isMaxClusterFailoverCountReach %t, isOneSlaveHeartbeatIncreasing %t, isMaxscaleSupectRunning %t",
	"ERR00025": "Could not get MaxScale maxinfo server list: %s",
	"ERR00026": "First node restarted is a slave, non interactive mode",
	"ERR00027": "Number of cluster failover exceeded",
	"ERR00028": "Slave %s can still communicate with the master",
	"ERR00029": "Time between failover to short",
	"ERR00030": "Maxscale %s can still communicate with the master",
	"ERR00031": "External API can still communicate with the master",
	"ERR00032": "No candidates found in slaves list",
}
