package cluster

var clusterError = map[string]string{
	"ERR00005": "Error getting privileges for user %s@%s: %s",
	"ERR00006": "User must have REPLICATION CLIENT privilege",
	"ERR00007": "User must have REPLICATION SLAVE privilege",
	"ERR00008": "User must have SUPER privilege",
	"ERR00009": "User must have RELOAD privilege",
	"ERR00011": "Multiple masters detected but explicity setup, setting the parameter",
	"ERR00012": "Could not detect a master",
	"ERR00013": "Binary log disabled on slave: %s",
	"ERR00014": "Error getting binlog dump count on server %s: %s",
	"ERR00015": "Error getting privileges for user %s on server %s: %s",
	"ERR00016": "Network issue - Master is unreachable but slaves are replicating",
	"ERR00017": "MaxScale no monitor capture",
	"ERR00018": "Could not connect to MaxScale: %s",
	"ERR00019": "Could not get MaxScale maxadmin server list: %s",
	"ERR00020": "Could not get MaxScale maxinfo server list: %s",
	"ERR00021": "All cluster down in non interactive mode",
	"ERR00022": "Constraint is blocking for failover isExternalOk %t,isActiveArbitration %t,isBeetwenFailoverTimeTooShort %t ,isMaxClusterFailoverCountReach %t, isOneSlaveHeartbeatIncreasing %t, isMaxscaleSupectRunning %t",
	"ERR00023": "Constraint is blocking state %s, conf.Interactive %t cluster.isMaxMasterFailedCountReach %t",
	"ERR00024": "Constraint is blocking for failover isExternalOk %t,isActiveArbitration %t,isBeetwenFailoverTimeTooShort %t ,isMaxClusterFailoverCountReach %t, isOneSlaveHeartbeatIncreasing %t, isMaxscaleSupectRunning %t",
	"ERR00025": "Could not get MaxScale maxinfo server list: %s",
	"ERR00026": "Constraint is blocking for failover slave back isFirstSlave %t",
}
