// replication-manager - Replication Manager Monitoring and CLI for MariaDB and MySQL
// Copyright 2017-2021 SIGNAL18 CLOUD SAS
// This source code is licensed under the GNU General Public License, version 3.

// plugin_sign.go — CLI commands for plugin signing key management.
//
// Security model:
//
//	The private key stays on the build/CI machine only.
//	The public key is deployed on every repman server and referenced via
//	'plugin-signing-public-key' in config.toml.
//
//	.sig files are placed in <ShareDir>/plugins/ — part of the repman
//	installation — NOT in the .pull repository.  This means an attacker
//	who can write to .pull cannot forge a signature; they would need write
//	access to the repman installation itself.
//
// Workflow:
//
//  1. Generate keypair once on your build/CI machine:
//     replication-manager plugin-keygen \
//       --plugin-private-key /etc/repman-build/plugin-signing.key \
//       --plugin-public-key  /etc/replication-manager/plugin-signing.pub
//
//  2. Set in config.toml on every repman server:
//     plugin-signing-public-key = "/etc/replication-manager/plugin-signing.pub"
//
//  3. Sign each plugin binary on the build machine:
//     replication-manager plugin-sign \
//       --plugin-private-key /etc/repman-build/plugin-signing.key \
//       --sig-output-dir     /usr/share/replication-manager/plugins \
//       /path/to/plugin-my-rule
//     → writes /usr/share/replication-manager/plugins/plugin-my-rule.sig
//
//  4. Deploy the .sig files as part of the repman package/release
//     (e.g. include them in the rpm/deb alongside the repman binary).
//
//  5. Push ONLY the plugin binary (no .sig) to your private .pull repo:
//     your-private-repo/{cluster}/plugins/plugin-my-rule
//
//  6. On git pull repman copies the binary, reads the .sig from ShareDir,
//     verifies, and hot-reloads only if the signature is valid.

package server

import (
	"crypto/ed25519"
	"fmt"
	"log"
	"os"

	"github.com/spf13/cobra"
)

var (
	pluginPrivateKeyPath string
	pluginPublicKeyPath  string
	pluginSigOutputDir   string
)

func init() {
	rootCmd.AddCommand(pluginKeygenCmd)
	rootCmd.AddCommand(pluginSignCmd)

	pluginKeygenCmd.Flags().StringVar(&pluginPrivateKeyPath,
		"plugin-private-key", "/etc/replication-manager/plugin-signing.key",
		"Path to write the Ed25519 private key (keep on build machine only)")
	pluginKeygenCmd.Flags().StringVar(&pluginPublicKeyPath,
		"plugin-public-key", "/etc/replication-manager/plugin-signing.pub",
		"Path to write the Ed25519 public key (deploy to all repman servers)")

	pluginSignCmd.Flags().StringVar(&pluginPrivateKeyPath,
		"plugin-private-key", "/etc/replication-manager/plugin-signing.key",
		"Path to the Ed25519 private key generated by plugin-keygen")
	pluginSignCmd.Flags().StringVar(&pluginSigOutputDir,
		"sig-output-dir", "/usr/share/replication-manager/plugins",
		"Directory where .sig files are written (must be ShareDir/plugins on repman servers)")
}

var pluginKeygenCmd = &cobra.Command{
	Use:   "plugin-keygen",
	Short: "Generate an Ed25519 keypair for signing plugin binaries",
	Long: `Generates a new Ed25519 keypair used to sign plugin binaries.

The private key must stay on your build/CI machine only.
The public key must be deployed to every repman server and referenced via
the 'plugin-signing-public-key' config option.`,
	Run: func(cmd *cobra.Command, args []string) {
		pub, priv, err := ed25519.GenerateKey(nil)
		if err != nil {
			log.Fatalf("plugin-keygen: failed to generate key: %v", err)
		}
		if err := writeKeyFile(pluginPrivateKeyPath, priv, 0600); err != nil {
			log.Fatalf("plugin-keygen: cannot write private key to %s: %v", pluginPrivateKeyPath, err)
		}
		if err := writeKeyFile(pluginPublicKeyPath, pub, 0644); err != nil {
			log.Fatalf("plugin-keygen: cannot write public key to %s: %v", pluginPublicKeyPath, err)
		}
		fmt.Printf("Private key → %s  (build machine only — never commit or deploy)\n", pluginPrivateKeyPath)
		fmt.Printf("Public  key → %s  (deploy to all repman servers)\n", pluginPublicKeyPath)
		fmt.Println()
		fmt.Println("Add to config.toml on every repman server:")
		fmt.Printf("  plugin-signing-public-key = %q\n", pluginPublicKeyPath)
	},
}

var pluginSignCmd = &cobra.Command{
	Use:   "plugin-sign <binary> [<binary2> ...]",
	Short: "Sign plugin binaries — writes .sig files to sig-output-dir",
	Long: `Signs one or more plugin binaries and writes a <name>.sig file to
--sig-output-dir (default: ShareDir/plugins/).

The .sig files must be distributed as part of the repman release/package,
NOT committed to the .pull repository.  Only the unsigned binary goes into
the .pull repo.  This separation ensures an attacker who controls .pull
cannot forge a valid signature.`,
	Args: cobra.MinimumNArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		privBytes, err := os.ReadFile(pluginPrivateKeyPath)
		if err != nil {
			log.Fatalf("plugin-sign: cannot read private key %s: %v", pluginPrivateKeyPath, err)
		}
		if len(privBytes) != ed25519.PrivateKeySize {
			log.Fatalf("plugin-sign: invalid private key length %d (expected %d)",
				len(privBytes), ed25519.PrivateKeySize)
		}
		priv := ed25519.PrivateKey(privBytes)

		if err := os.MkdirAll(pluginSigOutputDir, 0755); err != nil {
			log.Fatalf("plugin-sign: cannot create sig output dir %s: %v", pluginSigOutputDir, err)
		}

		for _, binPath := range args {
			data, err := os.ReadFile(binPath)
			if err != nil {
				log.Printf("plugin-sign: cannot read %s: %v — skipping", binPath, err)
				continue
			}
			sig := ed25519.Sign(priv, data)

			// Write sig to sigOutputDir, not next to the binary.
			sigFile := pluginSigOutputDir + "/" + pluginNameFromPath(binPath) + ".sig"
			if err := os.WriteFile(sigFile, sig, 0644); err != nil {
				log.Printf("plugin-sign: cannot write %s: %v — skipping", sigFile, err)
				continue
			}
			fmt.Printf("Signed: %-40s  →  %s\n", binPath, sigFile)
		}
		fmt.Println()
		fmt.Printf("Deploy the .sig files in %s as part of the repman package.\n", pluginSigOutputDir)
		fmt.Println("Do NOT commit .sig files to the .pull repository.")
	},
}

func writeKeyFile(path string, key []byte, perm os.FileMode) error {
	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("file already exists: %s (delete it first to regenerate)", path)
	}
	return os.WriteFile(path, key, perm)
}

func pluginNameFromPath(path string) string {
	base := path
	for i := len(path) - 1; i >= 0; i-- {
		if path[i] == '/' || path[i] == '\\' {
			base = path[i+1:]
			break
		}
	}
	return base
}
