// replication-manager - Replication Manager Monitoring and CLI for MariaDB and MySQL
// Copyright 2017-2026 SIGNAL18 CLOUD SAS
// Authors: Guillaume Lefranc <guillaume@signal18.io>
//          Stephane Varoqui  <svaroqui@gmail.com>
// This source code is licensed under the GNU General Public License, version 3.

package server

import (
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"sort"
	"strings"

	"github.com/signal18/replication-manager/config"
	repmanmcp "github.com/signal18/replication-manager/mcp"
	"github.com/signal18/replication-manager/peer"
)

// Cloud18 for the MCP server (issue #1838): the same registration, subscription
// and marketplace operations as the REST /api/register* and /api/clusters/for-sale
// endpoints, exposed to an assistant. Authorization is the caller's global-admin-show
// grant for actions (AuthorizeMCPGlobal), any authenticated principal for reads.
//
// The GitLab password of a registration started from MCP is generated here and
// never leaves the server: it is stored in the config on success exactly as the
// REST flow does (cloud18-gitlab-password), the person resets it on
// gitlab.signal18.io if they ever need to log in there interactively.

// AuthorizeMCPGlobal reports whether the principal holds a grant on at least one
// cluster, token narrowing and scope applied (a token needs the "*" scope for
// repman-global operations). An empty grant means any authenticated principal.
func (repman *ReplicationManager) AuthorizeMCPGlobal(p *repmanmcp.Principal, grant string) bool {
	if p == nil {
		return false
	}
	if grant == "" {
		return true
	}
	ok := false
	switch p.AuthMethod {
	case "token":
		t, isToken := p.Auth.(*APIToken)
		if !isToken || t == nil || !t.IsGlobal() {
			break
		}
		for _, cl := range repman.Clusters {
			if u, found := cl.GetACLUser(repman.tokenPrincipalFor(t, cl)); found && u.Grants[grant] {
				ok = true
				break
			}
		}
	default:
		for _, cl := range repman.Clusters {
			if u, found := cl.APIUsers[p.User]; found && u.Grants[grant] {
				ok = true
				break
			}
		}
	}
	if !ok {
		repman.logSecurityEvent("mcp_denied", p.User, p.Remote, fmt.Sprintf("MCP %s denied: needs %s (global)", p.String(), grant))
	}
	return ok
}

// Cloud18Status describes the instance's Cloud18 connection.
func (repman *ReplicationManager) Cloud18Status() map[string]any {
	state, message, _ := repman.RegStatus.snapshot()
	return map[string]any{
		"registered":        repman.Conf.Cloud18,
		"uri":               repman.registeredInstanceURI(),
		"domain":            repman.Conf.Cloud18Domain,
		"subDomain":         repman.Conf.Cloud18SubDomain,
		"zone":              repman.Conf.Cloud18SubDomainZone,
		"gitlabUser":        repman.Conf.Cloud18GitUser,
		"subscriptionPlan":  repman.Conf.Cloud18SubscriptionPlan,
		"crmApi":            repman.crmBase(),
		"registrationState": state,
		"registrationMsg":   message,
		"peersDisabled":     repman.Conf.Cloud18DisablePeers,
		"forSaleDisabled":   repman.Conf.Cloud18DisableForSale,
	}
}

// Cloud18RegisterStatus returns the registration state machine.
func (repman *ReplicationManager) Cloud18RegisterStatus() map[string]any {
	state, message, result := repman.RegStatus.snapshot()
	out := map[string]any{"state": state, "message": message}
	if len(result) > 0 {
		out["result"] = json.RawMessage(result)
	}
	return out
}

func generateCloud18Password() (string, error) {
	b := make([]byte, 18)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return "Rm-" + base64.RawURLEncoding.EncodeToString(b), nil
}

// Cloud18Register starts the registration with a server-generated GitLab password.
func (repman *ReplicationManager) Cloud18Register(email, uri string) (map[string]any, error) {
	email = strings.TrimSpace(strings.ToLower(email))
	if email == "" || uri == "" {
		return nil, errors.New("email and uri are required")
	}
	domain, subdomain, zone, err := parseCloud18URI(uri)
	if err != nil {
		return nil, err
	}
	if repman.Conf.Cloud18 {
		return nil, fmt.Errorf("this instance is already registered as %s; unregister first", repman.registeredInstanceURI())
	}
	password, err := generateCloud18Password()
	if err != nil {
		return nil, err
	}
	status, body, err := repman.startCloud18Registration(email, domain, subdomain, zone, password)
	if err != nil {
		return nil, err
	}
	out := map[string]any{"crmStatus": status, "crmResponse": json.RawMessage(rawOrNull(body))}
	if status == http.StatusAccepted || status == http.StatusOK {
		out["state"] = RegStatePending
		out["next"] = fmt.Sprintf("%s must click the confirmation link GitLab just emailed; poll get-cloud18-register-status until complete (timeout %s). The GitLab password was generated by the server and stored on success; use 'forgot password' on gitlab.signal18.io to log in there.", email, confirmPollTimeout)
	} else {
		return out, fmt.Errorf("CRM refused the registration (HTTP %d): %s", status, strings.TrimSpace(string(body)))
	}
	return out, nil
}

// Cloud18RegisterConfirm runs step 2 with the password of the registration in
// progress (generated by Cloud18Register) or the one stored in the config.
func (repman *ReplicationManager) Cloud18RegisterConfirm(email, uri string) (map[string]any, error) {
	email = strings.TrimSpace(strings.ToLower(email))
	domain, subdomain, zone, err := parseCloud18URI(uri)
	if err != nil {
		return nil, err
	}
	password := repman.regPassword
	if password == "" {
		password = repman.Conf.GetDecryptedValue("cloud18-gitlab-password")
	}
	if password == "" {
		return nil, errors.New("no registration in progress on this instance: call cloud18-register first (the manual REST confirm takes the password explicitly)")
	}
	status, body, err := repman.confirmCloud18Registration(email, domain, subdomain, zone, password)
	if err != nil {
		return nil, err
	}
	out := map[string]any{"crmStatus": status, "crmResponse": json.RawMessage(rawOrNull(body))}
	if status != http.StatusCreated {
		return out, fmt.Errorf("CRM refused the confirmation (HTTP %d): %s", status, strings.TrimSpace(string(body)))
	}
	out["state"] = RegStateOK
	return out, nil
}

// Cloud18Unregister disconnects the instance from Cloud18.
func (repman *ReplicationManager) Cloud18Unregister() (map[string]any, error) {
	uri := repman.registeredInstanceURI()
	if !repman.Conf.Cloud18 || uri == "" {
		return nil, errors.New("not registered to Cloud18")
	}
	tok, err := repman.gitlabTokenFromConfig()
	if err != nil {
		return nil, err
	}
	status, body, err := crmUnregister(repman.crmBase(), tok, uri)
	if err != nil {
		return nil, fmt.Errorf("CRM unreachable: %s", err)
	}
	out := map[string]any{"crmStatus": status, "crmResponse": json.RawMessage(rawOrNull(body)), "uri": uri}
	if status != http.StatusOK {
		return out, fmt.Errorf("CRM refused the unregistration (HTTP %d): %s", status, strings.TrimSpace(string(body)))
	}
	repman.Conf.Cloud18 = false
	repman.LogModulePrintf(repman.Conf.Verbose, config.ConstLogModGeneral, config.LvlInfo, "unregister: Cloud18 disconnected for URI %s (MCP)", uri)
	return out, nil
}

// Cloud18SubscriptionPlans lists the instance plans offered by the CRM.
func (repman *ReplicationManager) Cloud18SubscriptionPlans() (json.RawMessage, error) {
	status, body, err := crmGetPlans(repman.crmBase())
	if err != nil {
		return nil, fmt.Errorf("CRM unreachable: %s", err)
	}
	if status != http.StatusOK {
		return nil, fmt.Errorf("CRM answered HTTP %d: %s", status, strings.TrimSpace(string(body)))
	}
	return json.RawMessage(rawOrNull(body)), nil
}

// Cloud18Subscription returns the current plan of the instance from the CRM.
func (repman *ReplicationManager) Cloud18Subscription() (json.RawMessage, error) {
	uri := repman.registeredInstanceURI()
	if !repman.Conf.Cloud18 || uri == "" {
		return nil, errors.New("not registered to Cloud18")
	}
	tok, err := repman.gitlabTokenFromConfig()
	if err != nil {
		return nil, err
	}
	status, body, err := crmGetSubscription(repman.crmBase(), tok, uri)
	if err != nil {
		return nil, fmt.Errorf("CRM unreachable: %s", err)
	}
	if status != http.StatusOK {
		return nil, fmt.Errorf("CRM answered HTTP %d: %s", status, strings.TrimSpace(string(body)))
	}
	return json.RawMessage(rawOrNull(body)), nil
}

// Cloud18ChangeSubscription switches the instance plan.
func (repman *ReplicationManager) Cloud18ChangeSubscription(plan string) (map[string]any, error) {
	uri := repman.registeredInstanceURI()
	if !repman.Conf.Cloud18 || uri == "" {
		return nil, errors.New("not registered to Cloud18")
	}
	plan = strings.TrimSpace(strings.ToLower(plan))
	if plan == "" {
		return nil, errors.New("plan is required (free, support, support-services, partner)")
	}
	tok, err := repman.gitlabTokenFromConfig()
	if err != nil {
		return nil, err
	}
	status, body, err := crmChangeSubscription(repman.crmBase(), tok, uri, plan)
	if err != nil {
		return nil, fmt.Errorf("CRM unreachable: %s", err)
	}
	out := map[string]any{"crmStatus": status, "crmResponse": json.RawMessage(rawOrNull(body)), "uri": uri, "plan": plan}
	if status == http.StatusOK || status == http.StatusCreated || status == http.StatusAccepted {
		repman.persistInstanceSubscriptionPlan(plan, uri)
		return out, nil
	}
	return out, fmt.Errorf("CRM refused the plan change (HTTP %d): %s", status, strings.TrimSpace(string(body)))
}

// Cloud18ClustersForSale returns the marketplace catalogue as the REST endpoint does.
func (repman *ReplicationManager) Cloud18ClustersForSale() ([]*peer.PeerCluster, error) {
	if repman.PeerManager == nil {
		return nil, errors.New("peer manager not started (not registered to Cloud18?)")
	}
	plan := repman.Conf.Cloud18SubscriptionPlan
	if repman.Conf.Cloud18DisableForSale && plan != "" && plan != "free" {
		return []*peer.PeerCluster{}, nil
	}
	raw, err := repman.PeerManager.GetSaleClustersJSON()
	if err != nil {
		return nil, err
	}
	var list []*peer.PeerCluster
	if err := json.Unmarshal(raw, &list); err != nil {
		return nil, err
	}
	return list, nil
}

// Cloud18Infrastructures groups the clusters for sale by their api-public-url.
func (repman *ReplicationManager) Cloud18Infrastructures() ([]repmanmcp.Cloud18Infrastructure, error) {
	list, err := repman.Cloud18ClustersForSale()
	if err != nil {
		return nil, err
	}
	byURL := map[string]*repmanmcp.Cloud18Infrastructure{}
	for _, c := range list {
		if c == nil || c.ApiPublicUrl == "" {
			continue
		}
		infra, ok := byURL[c.ApiPublicUrl]
		if !ok {
			infra = &repmanmcp.Cloud18Infrastructure{ApiPublicUrl: c.ApiPublicUrl}
			byURL[c.ApiPublicUrl] = infra
		}
		infra.Clusters++
		infra.ClusterNames = append(infra.ClusterNames, c.ClusterName)
		infra.Orchestrators = appendUnique(infra.Orchestrators, c.ProvOrchestrator)
		infra.ServicePlans = appendUnique(infra.ServicePlans, c.ProvServicePlan)
	}
	out := make([]repmanmcp.Cloud18Infrastructure, 0, len(byURL))
	for _, infra := range byURL {
		sort.Strings(infra.ClusterNames)
		out = append(out, *infra)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ApiPublicUrl < out[j].ApiPublicUrl })
	return out, nil
}

func appendUnique(list []string, v string) []string {
	if v == "" {
		return list
	}
	for _, x := range list {
		if x == v {
			return list
		}
	}
	return append(list, v)
}

func rawOrNull(b []byte) []byte {
	if len(b) == 0 || !json.Valid(b) {
		q, _ := json.Marshal(strings.TrimSpace(string(b)))
		return q
	}
	return b
}
