// replication-manager - Replication Manager Monitoring and CLI for MariaDB and MySQL
// Copyright 2017-2026 SIGNAL18 CLOUD SAS
// Authors: Guillaume Lefranc <guillaume@signal18.io>
//          Stephane Varoqui  <svaroqui@gmail.com>
// This source code is licensed under the GNU General Public License, version 3.

package repmanmcp

import (
	"context"
	"fmt"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
)

// Cloud18 tools (issue #1838): registration of the instance with Signal18
// Cloud18, subscription plan, and the marketplace catalogue. Repman-global, so
// they carry no cluster_name; the ACL is the caller's global-admin-show grant
// for actions and any authenticated principal for reads (see toolACLPaths).
// Naming follows the rest of the catalogue: list-/get- for reads, noun-verb
// for actions.

func (s *MCPServer) registerCloud18Tools() {
	s.addTool(
		mcp.NewTool("get-cloud18-status",
			mcp.WithDescription("Whether this replication-manager instance is registered with Signal18 Cloud18, its URI (domain.subdomain.zone), GitLab user, subscription plan, the CRM API in use, the state of a registration in progress, and whether peers and the marketplace are disabled. Call this first before any other cloud18-* tool."),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return mcp.NewToolResultText(toJSON(s.repman.Cloud18Status())), nil
		},
	)

	s.addTool(
		mcp.NewTool("get-cloud18-register-status",
			mcp.WithDescription("State of the Cloud18 registration started with cloud18-register: idle, pending (waiting for the confirmation email to be clicked), complete, timeout or error, with the message and the CRM result. Poll it after cloud18-register."),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return mcp.NewToolResultText(toJSON(s.repman.Cloud18RegisterStatus())), nil
		},
	)

	s.addTool(
		mcp.NewTool("cloud18-register",
			mcp.WithDescription("Register this instance with Signal18 Cloud18 (free plan): creates the Signal18 GitLab account for the email, sends a confirmation email, and connects the instance once the link is clicked (config backup in GitLab, community plugins, cluster role sharing, marketplace access). The URI is domain.subdomain.zone: domain = the client name given by Signal18, subdomain = your choice, one per instance (e.g. prod1), zone = your choice (e.g. fr-1). The GitLab password is generated by the server and never returned; the person uses 'forgot password' on gitlab.signal18.io if they need to log in there. Needs the global-admin-show grant; a token also needs the every-cluster scope."),
			mcp.WithString("email", mcp.Required(), mcp.Description("Email of the person registering, receives the confirmation link")),
			mcp.WithString("uri", mcp.Required(), mcp.Description("Instance URI domain.subdomain.zone, e.g. mycompany.prod1.fr-1")),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			out, err := s.repman.Cloud18Register(req.GetString("email", ""), req.GetString("uri", ""))
			if err != nil {
				return mcp.NewToolResultErrorf("%s%s", err.Error(), detail(out)), nil
			}
			return mcp.NewToolResultText(toJSON(out)), nil
		},
	)

	s.addTool(
		mcp.NewTool("cloud18-register-confirm",
			mcp.WithDescription("Manual second step of the registration: run it if the confirmation email was clicked after the background wait timed out. Uses the password of the registration in progress. Needs the global-admin-show grant."),
			mcp.WithString("email", mcp.Required(), mcp.Description("Email used at cloud18-register")),
			mcp.WithString("uri", mcp.Required(), mcp.Description("Instance URI used at cloud18-register")),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			out, err := s.repman.Cloud18RegisterConfirm(req.GetString("email", ""), req.GetString("uri", ""))
			if err != nil {
				return mcp.NewToolResultErrorf("%s%s", err.Error(), detail(out)), nil
			}
			return mcp.NewToolResultText(toJSON(out)), nil
		},
	)

	s.addTool(
		mcp.NewTool("cloud18-unregister",
			mcp.WithDescription("Disconnect this instance from Cloud18: the instance is removed on the CRM side and the local Cloud18 state is cleared, the GitLab account stays. Needs the global-admin-show grant."),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			out, err := s.repman.Cloud18Unregister()
			if err != nil {
				return mcp.NewToolResultErrorf("%s%s", err.Error(), detail(out)), nil
			}
			return mcp.NewToolResultText(toJSON(out)), nil
		},
	)

	s.addTool(
		mcp.NewTool("list-cloud18-subscription-plans",
			mcp.WithDescription("The instance subscription plans offered by Signal18 (free, support, support-services, partner) with what each unlocks, as published by the CRM."),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			out, err := s.repman.Cloud18SubscriptionPlans()
			if err != nil {
				return mcp.NewToolResultError(err.Error()), nil
			}
			return mcp.NewToolResultText(string(out)), nil
		},
	)

	s.addTool(
		mcp.NewTool("get-cloud18-subscription",
			mcp.WithDescription("The current subscription plan of this instance as known by the CRM (the instance must be registered)."),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			out, err := s.repman.Cloud18Subscription()
			if err != nil {
				return mcp.NewToolResultError(err.Error()), nil
			}
			return mcp.NewToolResultText(string(out)), nil
		},
	)

	s.addTool(
		mcp.NewTool("cloud18-change-subscription",
			mcp.WithDescription("Change the subscription plan of this instance: free, support, support-services or partner (see list-cloud18-subscription-plans). Paid plans are invoiced by Signal18. Needs the global-admin-show grant."),
			mcp.WithString("plan", mcp.Required(), mcp.Description("free, support, support-services or partner")),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			out, err := s.repman.Cloud18ChangeSubscription(req.GetString("plan", ""))
			if err != nil {
				return mcp.NewToolResultErrorf("%s%s", err.Error(), detail(out)), nil
			}
			return mcp.NewToolResultText(toJSON(out)), nil
		},
	)

	s.addTool(
		mcp.NewTool("list-cloud18-clusters-for-sale",
			mcp.WithDescription("The Cloud18 marketplace catalogue: every database cluster offered for sale by Signal18 and partner infrastructures, with its api-public-url (the infrastructure), orchestrator, service plan, sizing (cores, memory, disk, IOPS), topology and health. Requires the instance to be registered."),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			out, err := s.repman.Cloud18ClustersForSale()
			if err != nil {
				return mcp.NewToolResultError(err.Error()), nil
			}
			return mcp.NewToolResultText(toJSON(out)), nil
		},
	)

	s.addTool(
		mcp.NewTool("list-cloud18-infrastructures",
			mcp.WithDescription("The infrastructures of the Cloud18 marketplace: one entry per distinct api-public-url among the clusters for sale, with the number and names of the clusters it offers, its orchestrators and service plans. Requires the instance to be registered."),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			out, err := s.repman.Cloud18Infrastructures()
			if err != nil {
				return mcp.NewToolResultError(err.Error()), nil
			}
			return mcp.NewToolResultText(toJSON(out)), nil
		},
	)

	s.addTool(
		mcp.NewTool("cloud18-create-cluster",
			mcp.WithDescription("Create a database cluster on a Cloud18 infrastructure (self-service): as this instance's Cloud18 identity, on the partner's replication-manager, create the cluster on the infrastructure's default unit plan (DBU/APU/BKU, no service plan), set the database image, add the database nodes, the proxy and the apps from their templates, and provision. Without confirm=true it only returns the plan: services to create, the infrastructure's self-service status for this identity (enabled, per-user limit, remaining slots). With confirm=true it creates: this is billable consumption on the infrastructure; the partner is informed. The partner enforces a per-user limit (3 by default). Needs the global-admin-show grant here; a token also needs the every-cluster scope."),
			mcp.WithString("infrastructure", mcp.Description("api-public-url of the infrastructure, from list-cloud18-infrastructures; empty = this instance, as yourself")),
			mcp.WithString("cluster_name", mcp.Required(), mcp.Description("Name of the new cluster (letters, digits, dashes)")),
			mcp.WithString("db_image", mcp.Description("Database docker image, default mariadb:lts (latest MariaDB long-term-support release)")),
			mcp.WithNumber("db_count", mcp.Description("Number of database nodes, default 2 (a master and a replica), max 5")),
			mcp.WithString("proxy", mcp.Description("haproxy (default), proxysql or none")),
			mcp.WithNumber("proxy_count", mcp.Description("Number of proxies, default 1, max 3")),
			mcp.WithString("apps", mcp.Description("Comma-separated app template names to deploy, resolved against the infrastructure's templates (phpmyadmin finds phpmyadmin/phpmyadmin); default phpmyadmin, none to deploy no app. The answer gives each app's URL, live once provisioned")),
			mcp.WithNumber("dbu", mcp.Description("DBU per database node; default the infrastructure's (prov-db-dbu). The cluster plan is db_count x dbu")),
			mcp.WithNumber("apu", mcp.Description("APU of the cluster's proxies and apps together; default the infrastructure's. Each app keeps at least 1 APU, the rest is shared by the proxies")),
			mcp.WithBoolean("confirm", mcp.Description("false (default): plan only, with the quote (monthly price at full capacity); true: create")),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			spec := cloud18SpecFrom(req)
			out, err := s.repman.Cloud18CreateCluster(principalFrom(ctx), spec, req.GetBool("confirm", false))
			if err != nil {
				return mcp.NewToolResultErrorf("%s\n%s", err.Error(), toJSON(out)), nil
			}
			return mcp.NewToolResultText(toJSON(out)), nil
		},
	)

	s.addTool(
		mcp.NewTool("list-cloud18-cluster-options",
			mcp.WithDescription("The possible values of a cluster request, dimension by dimension, before a quote or a creation: db_flavor (mariadb, mysql, percona, postgres), db_image (per flavor: the floating tags and every release line, LTS marked), topology (per flavor), proxy (and proxy_count), apps (the infrastructure's templates), dbu and apu (range, default, what is still free in the pool). Each value says whether cloud18-create-cluster can build it today (creatable) and why not. Filter one dimension with dimension and one flavor with db_flavor; apps, dbu and apu are read on the infrastructure, as yourself."),
			mcp.WithString("dimension", mcp.Description("db_flavor, db_image, topology, proxy, apps, dbu or apu; empty = every dimension")),
			mcp.WithString("db_flavor", mcp.Description("mariadb, mysql, percona or postgres; empty = every flavor")),
			mcp.WithString("infrastructure", mcp.Description("api-public-url of the infrastructure for apps, dbu and apu; empty = this instance, as yourself")),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			out, err := s.repman.Cloud18ClusterOptions(principalFrom(ctx), req.GetString("dimension", ""), req.GetString("db_flavor", ""), req.GetString("infrastructure", ""))
			if err != nil {
				return mcp.NewToolResultError(err.Error()), nil
			}
			return mcp.NewToolResultText(toJSON(out)), nil
		},
	)

	s.addTool(
		mcp.NewTool("get-cloud18-cluster-quote",
			mcp.WithDescription("Quote a database cluster on every infrastructure of the Cloud18 marketplace, as yourself, before creating it: per infrastructure, the units the request needs (DBU = db_count x dbu per database node, APU for the proxies and apps, the default BKU), whether they fit the free pool, whether you may create it there (or why not), and the MONTHLY PRICE AT FULL CAPACITY (the plan fully used the whole month) from that infrastructure's own unit prices, with its breakdown and the over-commit rate billed on top above the plan. Infrastructures where the creation is possible come first, cheapest first. Then create on the chosen one with cloud18-create-cluster and the same parameters."),
			mcp.WithString("db_image", mcp.Description("Database docker image, default mariadb:lts")),
			mcp.WithNumber("db_count", mcp.Description("Number of database nodes, default 2 (a master and a replica), max 5")),
			mcp.WithNumber("dbu", mcp.Description("DBU per database node; default each infrastructure's (prov-db-dbu)")),
			mcp.WithString("proxy", mcp.Description("haproxy (default), proxysql or none")),
			mcp.WithNumber("proxy_count", mcp.Description("Number of proxies, default 1, max 3")),
			mcp.WithString("apps", mcp.Description("Comma-separated app template names, default phpmyadmin, none for no app")),
			mcp.WithNumber("apu", mcp.Description("APU of the proxies and apps together; default each infrastructure's")),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			out, err := s.repman.Cloud18ClusterQuote(principalFrom(ctx), cloud18SpecFrom(req))
			if err != nil {
				return mcp.NewToolResultError(err.Error()), nil
			}
			return mcp.NewToolResultText(toJSON(out)), nil
		},
	)

	s.addTool(
		mcp.NewTool("get-cloud18-infrastructures",
			mcp.WithDescription("Your access to every infrastructure of the Cloud18 marketplace, as yourself: for each one, an MCP server entry carrying your session there (your Cloud18 identity is valid on every public instance: this instance logs you in there as you, the same door as Enter in the dashboard; no account and no token are written on the infrastructure, only a session that expires), and your self-service status there: whether you may create a cluster and why not, the free, usable and planned DBU and APU, the default plan a cluster takes, the clusters you may still sponsor, and the default request: the cluster an empty request gets there, every parameter resolved (db_image, db_count, dbu per node, proxy, proxy_count, apps, apu, bku), the starting point for get-cloud18-cluster-quote and cloud18-create-cluster. Connect the assistant to the infrastructure's entry, create the cluster there with cloud18-create-cluster (you become its sponsor), then mint your durable token with cloud18-create-cluster-token. A local admin without a Cloud18 account acts as this instance's registered identity; a local user or an API token is refused with the way in. The session expires with the login (api-token-timeout hours) and is a secret like a token."),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			out, err := s.repman.Cloud18InfrastructuresAccess(principalFrom(ctx))
			if err != nil {
				return mcp.NewToolResultError(err.Error()), nil
			}
			return mcp.NewToolResultText(toJSON(out)), nil
		},
	)

	s.addTool(
		mcp.NewTool("get-cloud18-cluster",
			mcp.WithDescription("Read a cluster on a Cloud18 infrastructure as this instance's Cloud18 identity: provisioning state, health flags, servers, proxies and apps. Use it after cloud18-create-cluster to follow the provisioning."),
			mcp.WithString("infrastructure", mcp.Description("api-public-url of the infrastructure; empty = this instance, as yourself")),
			mcp.WithString("cluster_name", mcp.Required(), mcp.Description("Name of the cluster on that infrastructure")),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			out, err := s.repman.Cloud18GetCluster(principalFrom(ctx), req.GetString("infrastructure", ""), req.GetString("cluster_name", ""))
			if err != nil {
				return mcp.NewToolResultError(err.Error()), nil
			}
			return mcp.NewToolResultText(toJSON(out)), nil
		},
	)

	s.addTool(
		mcp.NewTool("get-cloud18-cluster-price",
			mcp.WithDescription("Get what a cluster costs this month on a Cloud18 infrastructure, in EUR, as that infrastructure's resource manager integrates it per monitoring period: the partner and the sponsors, and per unit family (database plan in DBU, stateful applications in DBU, applications and proxies in APU, local backups in BKU, archives in BAU) the plan, the over-commit and the under-commit in unit-months, the unit price, the EUR accrued, the current rate and the projection to the end of the month. Use it after cloud18-create-cluster or a plan change to tell the user what they will pay."),
			mcp.WithString("infrastructure", mcp.Description("api-public-url of the infrastructure; empty = this instance, as yourself")),
			mcp.WithString("cluster_name", mcp.Required(), mcp.Description("Name of the cluster on that infrastructure")),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			out, err := s.repman.Cloud18GetClusterPrice(principalFrom(ctx), req.GetString("infrastructure", ""), req.GetString("cluster_name", ""))
			if err != nil {
				return mcp.NewToolResultError(err.Error()), nil
			}
			return mcp.NewToolResultText(toJSON(out)), nil
		},
	)

	s.addTool(
		mcp.NewTool("cloud18-create-cluster-token",
			mcp.WithDescription("Mint, on a Cloud18 infrastructure and as this instance's Cloud18 identity (the sponsor of the cluster), an API token scoped to one cluster there, and return the infrastructure's MCP endpoint configuration to add as a second MCP server. This is how an assistant gets to operate a cluster created with cloud18-create-cluster: tokens never cross infrastructures, the sponsor mints one on the infrastructure that hosts the cluster. The token carries the sponsor's grants on that cluster, narrowed to 'grants' if given; it is returned once and not stored. Needs the global-admin-show grant here; a token also needs the every-cluster scope."),
			mcp.WithString("infrastructure", mcp.Description("empty = this instance, as yourself; else the api-public-url of the infrastructure hosting the cluster")),
			mcp.WithString("cluster_name", mcp.Required(), mcp.Description("Name of the cluster on that infrastructure")),
			mcp.WithString("label", mcp.Description("Token label, default assistant-<cluster>")),
			mcp.WithString("grants", mcp.Description("Compact grant prefixes to narrow to, space separated, e.g. 'db-show cluster-show'; empty = all the sponsor's grants on the cluster")),
			mcp.WithNumber("expire_days", mcp.Description("Validity in days; 0 = the infrastructure's default (120), -1 = never")),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			out, err := s.repman.Cloud18CreateClusterToken(principalFrom(ctx), req.GetString("infrastructure", ""), req.GetString("cluster_name", ""), req.GetString("label", ""), req.GetString("grants", ""), req.GetInt("expire_days", 0))
			if err != nil {
				return mcp.NewToolResultError(err.Error()), nil
			}
			return mcp.NewToolResultText(toJSON(out)), nil
		},
	)

	s.mcp.AddPrompt(
		mcp.NewPrompt("cloud18-onboarding",
			mcp.WithPromptDescription("Guide a person through registering this instance with Signal18 Cloud18 and choosing a plan"),
		),
		func(ctx context.Context, req mcp.GetPromptRequest) (*mcp.GetPromptResult, error) {
			return mcp.NewGetPromptResult(
				"Cloud18 onboarding",
				[]mcp.PromptMessage{
					mcp.NewPromptMessage(
						mcp.RoleUser,
						mcp.NewTextContent(`Help me connect this replication-manager instance to Signal18 Cloud18.

Follow these steps:

1. Call get-cloud18-status. If registered is true, report the URI and plan and stop unless I ask for a change.
2. Explain the URI: domain is the client name given by Signal18, subdomain is my choice and unique per instance (for example prod1), zone is my choice (for example fr-1). Ask me for the email to register and the URI.
3. Call cloud18-register with them. Tell me to click the confirmation link in the email; do not ask me for any password, the server generates it.
4. Poll get-cloud18-register-status every 20 seconds until the state is complete, timeout or error, and report the message. On timeout, once I confirm I clicked the link, call cloud18-register-confirm.
5. When complete, call list-cloud18-subscription-plans and summarise the plans in a few lines. Every instance starts on free; only change the plan with cloud18-change-subscription if I ask for it.
6. Finish with list-cloud18-infrastructures so I see which marketplace infrastructures are reachable from here.`),
					),
				},
			), nil
		},
	)
}

// detail appends the CRM status and response to an error text when present.
func detail(out map[string]any) string {
	if out == nil {
		return ""
	}
	if st, ok := out["crmStatus"]; ok {
		return fmt.Sprintf(" (crm status %v)", st)
	}
	return ""
}

// cloud18SpecFrom reads a cluster request from the arguments the create and quote tools share.
func cloud18SpecFrom(req mcp.CallToolRequest) Cloud18ClusterSpec {
	spec := Cloud18ClusterSpec{
		Infrastructure: req.GetString("infrastructure", ""),
		ClusterName:    req.GetString("cluster_name", ""),
		DBImage:        req.GetString("db_image", ""),
		DBCount:        req.GetInt("db_count", 0),
		Proxy:          req.GetString("proxy", ""),
		ProxyCount:     req.GetInt("proxy_count", 0),
		DBU:            req.GetInt("dbu", 0),
		APU:            req.GetInt("apu", 0),
	}
	if apps := req.GetString("apps", ""); apps != "" {
		spec.Apps = strings.Split(apps, ",")
	}
	return spec
}
