// replication-manager - Replication Manager Monitoring and CLI for MariaDB and MySQL
// Copyright 2017-2026 SIGNAL18 CLOUD SAS
// Authors: Guillaume Lefranc <guillaume@signal18.io>
//          Stephane Varoqui  <svaroqui@gmail.com>
// This source code is licensed under the GNU General Public License, version 3.

package repmanmcp

import (
	"context"
	"fmt"

	"github.com/mark3labs/mcp-go/mcp"
)

// Cloud18 tools (issue #1838): registration of the instance with Signal18
// Cloud18, subscription plan, and the marketplace catalogue. Repman-global, so
// they carry no cluster_name; the ACL is the caller's global-admin-show grant
// for actions and any authenticated principal for reads (see toolACLPaths).
// Naming follows the rest of the catalogue: list-/get- for reads, noun-verb
// for actions.

func (s *MCPServer) registerCloud18Tools() {
	s.addTool(
		mcp.NewTool("get-cloud18-status",
			mcp.WithDescription("Whether this replication-manager instance is registered with Signal18 Cloud18, its URI (domain.subdomain.zone), GitLab user, subscription plan, the CRM API in use, the state of a registration in progress, and whether peers and the marketplace are disabled. Call this first before any other cloud18-* tool."),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return mcp.NewToolResultText(toJSON(s.repman.Cloud18Status())), nil
		},
	)

	s.addTool(
		mcp.NewTool("get-cloud18-register-status",
			mcp.WithDescription("State of the Cloud18 registration started with cloud18-register: idle, pending (waiting for the confirmation email to be clicked), complete, timeout or error, with the message and the CRM result. Poll it after cloud18-register."),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return mcp.NewToolResultText(toJSON(s.repman.Cloud18RegisterStatus())), nil
		},
	)

	s.addTool(
		mcp.NewTool("cloud18-register",
			mcp.WithDescription("Register this instance with Signal18 Cloud18 (free plan): creates the Signal18 GitLab account for the email, sends a confirmation email, and connects the instance once the link is clicked (config backup in GitLab, community plugins, cluster role sharing, marketplace access). The URI is domain.subdomain.zone: domain = the client name given by Signal18, subdomain = your choice, one per instance (e.g. prod1), zone = your choice (e.g. fr-1). The GitLab password is generated by the server and never returned; the person uses 'forgot password' on gitlab.signal18.io if they need to log in there. Needs the global-admin-show grant; a token also needs the every-cluster scope."),
			mcp.WithString("email", mcp.Required(), mcp.Description("Email of the person registering, receives the confirmation link")),
			mcp.WithString("uri", mcp.Required(), mcp.Description("Instance URI domain.subdomain.zone, e.g. mycompany.prod1.fr-1")),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			out, err := s.repman.Cloud18Register(req.GetString("email", ""), req.GetString("uri", ""))
			if err != nil {
				return mcp.NewToolResultErrorf("%s%s", err.Error(), detail(out)), nil
			}
			return mcp.NewToolResultText(toJSON(out)), nil
		},
	)

	s.addTool(
		mcp.NewTool("cloud18-register-confirm",
			mcp.WithDescription("Manual second step of the registration: run it if the confirmation email was clicked after the background wait timed out. Uses the password of the registration in progress. Needs the global-admin-show grant."),
			mcp.WithString("email", mcp.Required(), mcp.Description("Email used at cloud18-register")),
			mcp.WithString("uri", mcp.Required(), mcp.Description("Instance URI used at cloud18-register")),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			out, err := s.repman.Cloud18RegisterConfirm(req.GetString("email", ""), req.GetString("uri", ""))
			if err != nil {
				return mcp.NewToolResultErrorf("%s%s", err.Error(), detail(out)), nil
			}
			return mcp.NewToolResultText(toJSON(out)), nil
		},
	)

	s.addTool(
		mcp.NewTool("cloud18-unregister",
			mcp.WithDescription("Disconnect this instance from Cloud18: the instance is removed on the CRM side and the local Cloud18 state is cleared, the GitLab account stays. Needs the global-admin-show grant."),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			out, err := s.repman.Cloud18Unregister()
			if err != nil {
				return mcp.NewToolResultErrorf("%s%s", err.Error(), detail(out)), nil
			}
			return mcp.NewToolResultText(toJSON(out)), nil
		},
	)

	s.addTool(
		mcp.NewTool("list-cloud18-subscription-plans",
			mcp.WithDescription("The instance subscription plans offered by Signal18 (free, support, support-services, partner) with what each unlocks, as published by the CRM."),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			out, err := s.repman.Cloud18SubscriptionPlans()
			if err != nil {
				return mcp.NewToolResultError(err.Error()), nil
			}
			return mcp.NewToolResultText(string(out)), nil
		},
	)

	s.addTool(
		mcp.NewTool("get-cloud18-subscription",
			mcp.WithDescription("The current subscription plan of this instance as known by the CRM (the instance must be registered)."),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			out, err := s.repman.Cloud18Subscription()
			if err != nil {
				return mcp.NewToolResultError(err.Error()), nil
			}
			return mcp.NewToolResultText(string(out)), nil
		},
	)

	s.addTool(
		mcp.NewTool("cloud18-change-subscription",
			mcp.WithDescription("Change the subscription plan of this instance: free, support, support-services or partner (see list-cloud18-subscription-plans). Paid plans are invoiced by Signal18. Needs the global-admin-show grant."),
			mcp.WithString("plan", mcp.Required(), mcp.Description("free, support, support-services or partner")),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			out, err := s.repman.Cloud18ChangeSubscription(req.GetString("plan", ""))
			if err != nil {
				return mcp.NewToolResultErrorf("%s%s", err.Error(), detail(out)), nil
			}
			return mcp.NewToolResultText(toJSON(out)), nil
		},
	)

	s.addTool(
		mcp.NewTool("list-cloud18-clusters-for-sale",
			mcp.WithDescription("The Cloud18 marketplace catalogue: every database cluster offered for sale by Signal18 and partner infrastructures, with its api-public-url (the infrastructure), orchestrator, service plan, sizing (cores, memory, disk, IOPS), topology and health. Requires the instance to be registered."),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			out, err := s.repman.Cloud18ClustersForSale()
			if err != nil {
				return mcp.NewToolResultError(err.Error()), nil
			}
			return mcp.NewToolResultText(toJSON(out)), nil
		},
	)

	s.addTool(
		mcp.NewTool("list-cloud18-infrastructures",
			mcp.WithDescription("The infrastructures of the Cloud18 marketplace: one entry per distinct api-public-url among the clusters for sale, with the number and names of the clusters it offers, its orchestrators and service plans. Requires the instance to be registered."),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			out, err := s.repman.Cloud18Infrastructures()
			if err != nil {
				return mcp.NewToolResultError(err.Error()), nil
			}
			return mcp.NewToolResultText(toJSON(out)), nil
		},
	)

	s.mcp.AddPrompt(
		mcp.NewPrompt("cloud18-onboarding",
			mcp.WithPromptDescription("Guide a person through registering this instance with Signal18 Cloud18 and choosing a plan"),
		),
		func(ctx context.Context, req mcp.GetPromptRequest) (*mcp.GetPromptResult, error) {
			return mcp.NewGetPromptResult(
				"Cloud18 onboarding",
				[]mcp.PromptMessage{
					mcp.NewPromptMessage(
						mcp.RoleUser,
						mcp.NewTextContent(`Help me connect this replication-manager instance to Signal18 Cloud18.

Follow these steps:

1. Call get-cloud18-status. If registered is true, report the URI and plan and stop unless I ask for a change.
2. Explain the URI: domain is the client name given by Signal18, subdomain is my choice and unique per instance (for example prod1), zone is my choice (for example fr-1). Ask me for the email to register and the URI.
3. Call cloud18-register with them. Tell me to click the confirmation link in the email; do not ask me for any password, the server generates it.
4. Poll get-cloud18-register-status every 20 seconds until the state is complete, timeout or error, and report the message. On timeout, once I confirm I clicked the link, call cloud18-register-confirm.
5. When complete, call list-cloud18-subscription-plans and summarise the plans in a few lines. Every instance starts on free; only change the plan with cloud18-change-subscription if I ask for it.
6. Finish with list-cloud18-infrastructures so I see which marketplace infrastructures are reachable from here.`),
					),
				},
			), nil
		},
	)
}

// detail appends the CRM status and response to an error text when present.
func detail(out map[string]any) string {
	if out == nil {
		return ""
	}
	if st, ok := out["crmStatus"]; ok {
		return fmt.Sprintf(" (crm status %v)", st)
	}
	return ""
}
