// replication-manager - Replication Manager Monitoring and CLI for MariaDB and MySQL
// Copyright 2017-2021 SIGNAL18 CLOUD SAS
// Authors: Guillaume Lefranc <guillaume@signal18.io>
//
//	Stephane Varoqui  <svaroqui@gmail.com>
//
// This source code is licensed under the GNU General Public License, version 3.
// Redistribution/Reuse of this code is permitted under the GNU v3 license, as
// an additional term, ALL code must carry the original Author(s) credit in comment form.
// See LICENSE in this directory for the integral text.
package config

var ClusterError = map[string]string{
	"APPERR001": "Error connecting to application %s. Err: %s",
	"APPERR002": "Unexpected status for application %s. Code: %d",
	"APPERR003": "Error connecting to application %s via TCP. Err: %s",
	"APPERR004": "Unsupported protocol %s for application %s",
	"APPERR005": "Gateway route conflict for application %s: %s — gateway routes blocked, fix route config to resolve",
	"APPERR006": "Failed to create provision cookie for application %s: %s",
	"CREDIT01":  "Credit cap (%d) exceeded by planned allocation (%d). Over-subscription is allowed; cap auto-rebases to actual usage on successful provision.",
	"CREDIT02":  "Application %s has negative planned credit (%d). Please check the configuration.",
	"CREDIT03":  "Application %s has negative used credit (%d). Please check the configuration.",
	"CREDIT04":  "Application %s has planned credit (%d) not equal to used credit (%d). Please provision the application again to implement the changes.",
	"ERR00001":  "Monitor freeze while running critical section",
	"ERR00002":  "Waiting for a user manual failover",
	"ERR00004":  "Database %s access denied: %s",
	"ERR00005":  "Could not get privileges for user %s@%s: %s",
	"ERR00006":  "User must have REPLICATION CLIENT privilege on %s",
	"ERR00007":  "User must have REPLICATION SLAVE privilege on %s",
	"ERR00008":  "User must have SUPER privilege on %s",
	"ERR00009":  "User must have RELOAD privilege on %s",
	"ERR00010":  "Could not find a slave in topology",
	"ERR00011":  "Found multiple masters in topology but not explicitly setup",
	"ERR00012":  "Could not find a master in topology",
	"ERR00013":  "Binary log disabled on slave: %s",
	"ERR00014":  "Could not get binlog dump count on server %s: %s",
	"ERR00015":  "Could not get privileges for user %s on server %s: %s",
	"ERR00016":  "Master is unreachable but slaves are replicating",
	"ERR00017":  "Unable to fetch MaxScale monitoring information",
	"ERR00018":  "Could not connect to MaxScale: %s",
	"ERR00019":  "Could not get MaxScale maxadmin server list: %s",
	"ERR00020":  "Could not get MaxScale maxinfo server list: %s",
	"ERR00021":  "Cluster state down",
	"ERR00022":  "Running in passive mode",
	"ERR00023":  "Constraint failed: state %s, conf.Interactive %t cluster.isMaxMasterFailedCountReach %t",
	"ERR00024":  "Constraint failed: isExternalOk %t,isActiveArbitration %t,isBeetwenFailoverTimeTooShort %t ,isMaxClusterFailoverCountReach %t, isOneSlaveHeartbeatIncreasing %t, isMaxscaleSupectRunning %t",
	"ERR00025":  "Could not get MaxScale maxinfo server list: %s",
	"ERR00026":  "First node restarted is a slave, non-interactive mode",
	"ERR00027":  "Number of cluster failovers exceeded",
	"ERR00028":  "Slave %s can still communicate with the master",
	"ERR00029":  "Time between failovers too short",
	"ERR00030":  "Maxscale %s can still communicate with the master",
	"ERR00031":  "External API can still communicate with the master",
	"ERR00032":  "No candidates found in slaves list",
	"ERR00033":  "Skip slave in election %s: has no master log file, slave might have failed",
	"ERR00034":  "Skip slave in election %s: not electable for switchover",
	"ERR00035":  "Skip slave in election %s is multi-master and is already the master",
	"ERR00036":  "Skip slave in election %s is relay",
	"ERR00037":  "Skip slave in election %s: in ignore list",
	"ERR00038":  "Skip slave in election %s: not electable for failover",
	"ERR00039":  "Skip slave in election %s: not electable",
	"ERR00040":  "Skip slave in election %s does not ping or has no binlogs",
	"ERR00041":  "Skip slave in election %s has more than %d seconds of replication delay (%d)",
	"ERR00042":  "Skip slave in election %s SQL Thread is stopped",
	"ERR00043":  "Skip slave in election %s Semisync report unsynced",
	"ERR00044":  "Can't connect to OpenSVC collector %s",
	"ERR00045":  "Found forbidden relay topology, trying to fix",
	"ERR00046":  "Can't fix relay topology: high replication delay",
	"ERR00047":  "Skip slave in election %s - Maintenance mode",
	"ERR00048":  "Broken multi master ring",
	"ERR00049":  "Waiting old master to rejoin in positional mode to rejoin slave",
	"ERR00050":  "Can't connect to proxy %s",
	"ERR00051":  "ProxySQL connection error: %s",
	"ERR00052":  "Could not get stats from HAProxy: %s",
	"ERR00053":  "ProxySQL can't load users (%s)",
	"ERR00054":  "ProxySQL can't add user (%s)",
	"ERR00055":  "Arbitrator unreachable (%s)",
	"ERR00056":  "Master user %s is not defined on replication candidate %s",
	"ERR00057":  "Database duplicate users not allowed in proxysql %s",
	"ERR00058":  "Sphinx connection error: %s",
	"ERR00059":  "Ignored server %s not found in configured server list",
	"ERR00060":  "Too many non-closed tasks in scheduler, donor may not work on server %s",
	"ERR00061":  "No user:password credential specified",
	"ERR00062":  "DNS resolution for host %s error %s",
	"ERR00063":  "Extra master in master-slave topology, rejoining after split-brain",
	"ERR00064":  "Server %s is not a slave of declared master %s, and replication no-relay is enabled: pointing to %s",
	"ERR00065":  "No crash found on current master when rejoining slave %s to %s",
	"ERR00066":  "No crash found on current master when rejoining standalone %s to %s",
	"ERR00067":  "Found slave to rejoin %s: slave was previously in state %s, replication IO thread %s, currently pointing to %s",
	"ERR00068":  "Arbitration loser",
	"ERR00069":  "ProxySQL could not set %s as reader (%s): server is in a different state than OFFLINE_HARD",
	"ERR00070":  "ProxySQL could not set %s as reader (%s): server is in a different state than ONLINE",
	"ERR00071":  "ProxySQL %s could not set discovered master %s as writer (%s)",
	"ERR00072":  "ProxySQL %s could not set discovered slave %s as reader (%s)",
	"ERR00073":  "Could not get events on server %s",
	"ERR00074":  "Preferred server %s not found in configured server list",
	"ERR00075":  "Can't fetch Processlist %s",
	"ERR00076":  "Connections reach 80 percent threshold: %s",
	"ERR00077":  "All databases state down",
	"ERR00078":  "Could not resolve IP from connection %s@%s: with hostname %s on server %s",
	"ERR00079":  "Disk %s usage high on %s",
	"ERR00080":  "Connection use old TLS keys on %s",
	"ERR00081":  "Connection use no TLS keys on %s",
	"ERR00082":  "Could not get agents from orchestrator %s",
	"ERR00083":  "Different cluster uuid found on %s:%s %s:%s",
	"ERR00084":  "Cluster had no master when slave %s was started",
	"ERR00085":  "No replica found for routing reads",
	"ERR00086":  "Sharding proxy refresh: no database monitor initialized yet",
	"ERR00087":  "Skip slave in election %s IO Thread is stopped with valid leader",
	"ERR00088":  "Authentication error in replication IO thread",
	"ERR00089":  "Authentication error to Vault %s",
	"ERR00090":  "Monitoring save config enabled but no encryption key for password, see the keygen command",
	"ERR00091":  "Proxysql %s found active server %s as OFFLINE_SOFT in ProxySQL.",
	"ERR00092":  "Cluster [%s] topology (%s) does not match target topology (%s).",
	"ERR00093":  "ProxySQL %s is routing reads to master with no slaves and found no active reader, but bootstrap is turned off.",
	"ERR00094":  "Proxysql %s can not set %s as OFFLINE_SOFT: %s",
	"ERR00095":  "ProxySQL %s could not load servers to runtime: %s",
	"ERR00096":  "Proxysql %s can not save changes to disk: %s",
	"ERR00097":  "Auto failover locked with false positive conditions: %v",
	"ERR00098":  "Failed to enable GTID Mode on master node. Err: %s",
	"ERR00099":  "Failed to enable GTID Mode on slave %s. Err: %s",
	"ERR00100":  "Cluster is in switchover. Switchover started at %s",
	"ERR00101":  "Cluster DB user is same as replication user, but with different password",
	"ERR00102":  "Jobs unable to connect to db in %s",
	"ERR00103":  "Skip slave in election %s data diverge in checksum",
	"ERR00104":  "Arbitration split-brain resolution refused: instance not registered with a support or partner subscription",
	"ERR00105":  "Cluster is in standby mode — failover, switchover, rejoin and maintenance disabled",
	"WARN0022":  "Rejoining standalone server %s to master %s",
	"WARN0023":  "Number of failed master ping has been reached",
	"WARN0045":  "Provision task is in queue",
	"WARN0046":  "Provision task is waiting",
	"WARN0047":  "Enterprise provision of MariaDB Sharding Cluster not yet implemented",
	"WARN0048":  "No semisync settings on slave %s",
	"WARN0049":  "No binlog format ROW on slave %s and flashback activated",
	"WARN0050":  "No Heartbeat <= 1s on slave %s",
	"WARN0051":  "No GTID replication on slave %s",
	"WARN0052":  "No InnoDB durability on slave %s",
	"WARN0053":  "No replication checksum on slave %s",
	"WARN0054":  "No log of replication queries in slow query on slave %s",
	"WARN0055":  "ROW or MIXED binlog format and replicate_annotate_row_events is off on slave %s",
	"WARN0056":  "No compression of binlog on slave %s",
	"WARN0057":  "No log-slave-updates on slave %s",
	"WARN0058":  "No GTID strict mode on slave %s",
	"WARN0059":  "No replication crash-safe settings on slave %s",
	"WARN0060":  "No semisync settings on master %s",
	"WARN0061":  "No binlog format ROW on master %s and flashback activated",
	"WARN0062":  "No Heartbeat <= 1s on master %s",
	"WARN0064":  "No InnoDB durability on master %s",
	"WARN0065":  "No replication checksum on master %s",
	"WARN0066":  "No log of replication queries in slow query on master %s",
	"WARN0067":  "RBR is on and Binlog Annotation is off on master %s",
	"WARN0068":  "No compression of binlog on slave %s",
	"WARN0069":  "No log-slave-updates on master %s",
	"WARN0070":  "No GTID strict mode on master %s",
	"WARN0071":  "No replication crash-safe settings on master %s",
	"WARN0072":  "Running optimize table %s on server %s",
	"WARN0073":  "Running physical backup %s on server %s",
	"WARN0074":  "Reseeding physical backup %s on server %s",
	"WARN0075":  "Reseeding logical backup %s on server %s",
	"WARN0076":  "Flashback physical backup %s on server %s",
	"WARN0077":  "Flashback logical backup %s on server %s",
	"WARN0078":  "HAProxy version too old to get statistics",
	"WARN0079":  "Cluster is split-brain",
	"WARN0080":  "Cluster lost majority",
	"WARN0081":  "Cluster arbitrator error in reporting %s",
	"WARN0082":  "Cluster arbitrator error in arbitration %s",
	"WARN0083":  "Arbitration winner",
	"WARN0084":  "Variables differ between leader and replicas:\n%s",
	"WARN0085":  "Server %s in capture mode",
	"WARN0086":  "Checksum table waiting replication sync on slave %s",
	"WARN0087":  "Cluster same server_id %s %s",
	"WARN0088":  "High number of slow queries %s ",
	"WARN0089":  "ShardProxy Could not fetch master schemas %s",
	"WARN0090":  "Cluster arbitrator unreachable %s",
	"WARN0091":  "Server has errant transaction %s",
	"WARN0092":  "ProxySQL could not load query rules from runtime (%s)",
	"WARN0093":  "Restic fetch repo issue: %s",
	"WARN0094":  "Restic purge repo issue: %s",
	"WARN0095":  "Restic repository issue: %s",
	"WARN0096":  "Restart database server via job request %s",
	"WARN0097":  "Stop database server via job request %s",
	"WARN0098":  "ProxySQL could not load global variables from runtime (%s)",
	"WARN0099":  "Unable to load P12 certificate file %s. Err: %s",
	"WARN0100":  "No space left on device on %s",
	"WARN0101":  "Cluster does not have backup",
	"WARN0102":  "The config file must be merged because an immutable parameter has been changed. Use the config-merge command to save your changes.",
	"WARN0103":  "Enforcing replication mode idempotent but configured strict on server %s",
	"WARN0104":  "Enforcing replication mode strict but configured idempotent on server %s",
	"WARN0105":  "Force Binlog Purge is not yet available in multi master. Skipping",
	"WARN0106":  "Minimum number of connected replica(s) is not enough to initiate force purging. Minimum replicas: %d. Skipping",
	"WARN0107":  "Force Binlog Purge can not continue. Oldest binlog is still used by slaves: %s.%d. Skipping",
	"WARN0108":  "Default users still use default password. Please change the credentials for users: (%s)",
	"WARN0109":  "Error while checking master log file for purging in slave [%s] (%s) : %s\n",
	"WARN0110":  "Pending %s backup using %s for [%s] due to another job. Waiting...",
	"WARN0111":  "Cluster does not have logical backup",
	"WARN0112":  "Cluster does not have physical backup",
	"WARN0113":  "Failed to reseed physical backup on server %s, please check %s.out",
	"WARN0114":  "Unable to process job on slave %s due to SUPER READ ONLY",
	"WARN0115":  "Failed to create physical backup on server %s",
	"WARN0116":  "Failed to create logical backup on server %s",
	"WARN0117":  "Failed to get db client version on repman: %s",
	"WARN0118":  "Failed to get dump client version on repman: %s",
	"WARN0119":  "Failed to get binlog client version on repman: %s",
	"WARN0120":  "Failed to get mydumper version on repman: %s",
	"WARN0121":  "Failed to get restic version on repman: %s",
	"WARN0122":  "Metadata lock: %s",
	"WARN0123":  "Scheduler error on %s: Previous job with same type (%s) is still running",
	"WARN0124":  "Scheduler error on %s: Unable to set sql_log_bin = 0 for insert job (%s). Err: %s",
	"WARN0125":  "Scheduler error on %s: Unable to delete record for insert job (%s). Err: %s",
	"WARN0126":  "Scheduler error on %s: Unable to insert job (%s). Err: %s",
	"WARN0127":  "Scheduler error on %s: %s",
	"WARN0128":  "Provision is waiting for node %s refresh. Err: %s",
	"WARN0129":  "Provision is waiting for node %s running. Err: %s",
	"WARN0130":  "Error while rotating system logs on %s: %s. Err: %s",
	"WARN0131":  "Error while reading slow_log on %s. %s. Err: %s",
	"WARN0132":  "Unable to pull from repository %s. Err: %s",
	"WARN0133":  "Mydumper version %s is not compatible with MariaDB 10.7 and greater",
	"WARN0134":  "Restic repository is locked. Repo: %s",
	"WARN0135":  "Cluster has bad measurement in config file: %v",
	"WARN0137":  "Unable to open certificate file %s. Err: %s",
	"WARN0138":  "Unable to send mail alert. Please check your mailer configuration!",
	"WARN0139":  "Backup partition used size exceeds warning threshold. Mounts: %v Threshold: %d",
	"WARN0140":  "Backup partition used size exceeds critical threshold. %s Mounts: %v Threshold: %d",
	"WARN0141":  "Not enough free space estimated for %s logical backup on %s. Mount: %s Free: %s Required: %s",
	"WARN0142":  "Not enough free space estimated for %s physical backup on %s. Mount: %s Free: %s Required: %s",
	"WARN0143":  "Not enough free space estimated for binary log backup on %s. Mount: %s Free: %s Required: %s",
	"WARN0144":  "HAProxy inconsistent server ID between haproxy %s and cluster %s for host %s",
	"WARN0145":  "Failed to backup restic config file: %s",
	"WARN0146":  "Failed to restore restic config file: %s",
	"WARN0147":  "Current jobs script is different than the one in node %s. New: %s Current: %s. Err : %s",
	"WARN0148":  "Running job script upgrade on node %s.",
	"WARN0150":  "Orchestrator node(s) has reached minimum percentage of available memory threshold. Stats: %v",
	"WARN0151":  "Orchestrator node(s) has reached minimum percentage of available swap threshold. Stats: %v",
	"WARN0152":  "Orchestrator node(s) has reached max CPU load threshold. Stats: %v",
	"WARN0153":  "Missing or outdated scheduler jobs table on server %s. Err: %s",
	"WARN0155":  "Cluster is flagged for jobs upgrade",
	"WARN0156":  "Logical dump tool version %s is different than last backup version %s",
	"WARN0157":  "Physical dump tool version %s is different than last backup version %s",
	"WARN0158":  "Secret mismatch for job script on node %s. Err: %s",
	"WARN0159":  "Replication Manager used a deprecated configuration variable in default config. Keys: %s",
	"WARN0160":  "Replication Manager used a deprecated configuration variable in cluster %s. Keys: %s",
	"WARN0161":  "Working orchestrator agent is different than configured agent on server %s. Configured: %s Working: %s",
	"WARN0162":  "Working orchestrator agent is different than configured agent on proxy %s. Configured: %s Working: %s",
	"WARN0163":  "Cluster %s is flagged for schema monitoring",
	"WARN0164":  "Cluster %s has schema differences between master and slaves: %v",
	"WARN0165":  "Restart container cookie deferred on %s: %s",
	"WARN0166":  "Restic reseed queued on server %s (snapshot %s, method %s, strategy %s)",
	"WARN0167":  "Failed to get sysbench version on repman: %s",
	"WARN0168":  "New compliance moduleset available from back office (DB CRC: %08x → %08x, Proxy CRC: %08x → %08x). Accept the update via Settings to apply.",
	"WARN0169":  "On-premise SSH enabled but private key not found: %s. Generate a key for the repman user or set onpremise-ssh-private-key",
	"WARN0170":  "Configurator enabled (prov-db-config=true) but %s. Config tracking will not work until this is resolved.",
	"WARN0171":  "Server %s connection failed: %s",
	"WARN0172":  "Intervention scheduled at %s by %s: %s",
	"WARN0173":  "Intervention active since %s by %s: %s — notifications muted",
	"WARN0174":  "Waiting for global backup slot (%d/%d in use)",
	"WARN0175":  "Running logical backup %s on server %s",
	"WARN0176":  "Arbitration enabled but instance not registered — config sync disabled",
	// Log-tailer plugin state codes (WARN0200-WARN0299 reserved for logplugin)
	"WARN0200":  "Server %s has recent ERROR entries in database error log (last 24h)",
	"WARN0201":  "Server %s has recent SQL errors in SQL error log (last 24h)",
	"WARN0202":  "Server %s has recent slow queries in slow query log (last 24h)",
	"WARN0203":  "Log plugin execution error",
	"WARN0204":  "Server %s has new query templates in audit log not seen in baseline window",
	"WARN0205":  "Server %s has a log event spike detected vs dynamic multi-granularity baseline",
	"WARN0177":  "%d database(s) have configuration changes to resolve: %s",
	"WARN0178":  "On-premise SSH unreachable on %d node(s): %s",
	"WARN0179":  "%d database(s) differ from configurator generated config: %s",
	"WARN0180":  "%d database(s) have no deployed config received from dbjobs: %s",
	"WARN0181":  "SPLITBRAIN SIMULATION: simulated link cut active (%s) on this instance, auto-restore in %ds",
	"WARN0182":  "Failed to backup lost events of old master %s after failover — flashback rejoin impossible: %s",
	"WARN0206":  "Log plugin %s rejected: %s",
	"WARN0207":  "Plugin signature verification skipped: %s",
	// CINF: cluster observability statuses (INFO, state-as-tag) — each domain
	// state machine always explains why it may have nothing to report.
	"CINF0001":  "%s reporting limited: instance not registered on Cloud18",
	"CINF0002":  "No %s plugin enabled",
	"CINF0003":  "%s reporting disabled by variable %s",
	"CINF0004":  "%d %s plugin(s) loaded",
	"CINF0005":  "Next schema monitoring run at %s",
	"CINF0006":  "Schema monitoring in progress",
	"MDEV20821": "MariaDB version has replication issue https://jira.mariadb.org/browse/MDEV-20821",
	"MDEV28310": "MariaDB version has replication issue for non row format https://jira.mariadb.org/browse/MDEV-28310",
	"MDEV19577": "MariaDB version has replication issue for non row format https://jira.mariadb.org/browse/MDEV-19577",
}

var AppError = map[string]string{}

// GlobalError stores ReplicationManager-wide alert templates emitted by
// server-level supervision workflows.
var GlobalError = map[string]string{
	"GWARN001": "ReplicationManager detected stalled cluster heartbeat for %s",
	"GWARN002": "ReplicationManager git push reported warning-level failure: %s",
	"GWARN003": "ReplicationManager git pull reported warning-level failure: %s",
	"GWARN004": "ReplicationManager cannot reach GitLab identity provider: %s",
	"GWARN005": "ReplicationManager cannot reach Cloud18 CRM API: %s",
	"GERR001":  "ReplicationManager detected prolonged stalled cluster heartbeat for %s",
	"GERR002":  "ReplicationManager git push reported persistent failure: %s",
	"GERR003":  "ReplicationManager git pull reported persistent failure: %s",
	"GWARN006": "Server split-brain detected: peer unreachable, server status is %s",
	"GWARN007": "Server arbitration winner, all clusters set to active",
	"GWARN008": "Server arbitration loser, all clusters set to standby",
	"GERR004":  "Server arbitration not eligible: %s",
	"GERR005":  "ReplicationManager has %d cluster(s) with open blockers: %s",
	"GWARN012": "ReplicationManager cannot reach Meet support service: %s",
	"GWARN013": "Periodic %s task still running from previous cycle — possible network hang",
	"GWARN014": "Instance not registered on Cloud18 (%s) — some community features may be disabled",
	// GINF: informational operating modes (state-as-tag), never counted as alerts
	"GINF001":  "ReplicationManager has %d cluster(s) in standby pulling config from active peer: %s",
	"GINF002":  "ReplicationManager has %d unprovisioned cluster(s): %s",
	"GINF003":  "ReplicationManager has %d unmonitored cluster(s): %s",
	"GINF004":  "ReplicationManager registered on Cloud18 as %s (plan %s)",
	"GINF005":  "Support chat connected",
}
