## config.toml
## Example replication-manager configuration file

## change the service file  in /etc/systemd/system/replication-manager.service to looks like :
## replication-manager-osc  --config=./etc/config.toml.sample  --cluster=Cluster01,Cluster_Test_2_Nodes monitor

[ClusterTestGraphite]
title = "ClusterTestGraphite"
db-servers-hosts = "127.0.0.1:3310,127.0.0.1:3311"
db-servers-prefered-master = "127.0.0.1:3310"
db-servers-credential = "root:test"
db-servers-connect-timeout = 1
replication-credential = "root:test"
haproxy = true
haproxy-write-port = 3303
haproxy-read-port = 3302

[Default]
graphite-metrics = true
graphite-embedded = true
graphite-carbon-host = "127.0.0.1"
graphite-carbon-port = 2003
graphite-carbon-api-port = 10002
graphite-carbon-server-port = 10003
graphite-carbon-link-port = 7002
graphite-carbon-pickle-port = 2004
graphite-carbon-pprof-port = 7007
