// replication-manager - Replication Manager Monitoring and CLI for MariaDB and MySQL
// Copyright 2017-2021 SIGNAL18 CLOUD SAS
// Authors: Guillaume Lefranc <guillaume@signal18.io>
//          Stephane Varoqui  <svaroqui@gmail.com>
// This source code is licensed under the GNU General Public License, version 3.

package share

import (
	"strings"
	"testing"
)

// TestOpenSVCHaproxyModulesetUsesNonRootSafeSockets guards against the
// embedded OpenSVC HAProxy templates (opensvc/moduleset_mariadb.svc.mrm.proxy.json,
// var_name "proxy_cnf_haproxy" / "proxy_cnf_haproxy_runtime_api") regressing
// to a stats socket path under /run. A non-root HAProxy container (e.g.
// haproxy:3.4, uid 99) can't create a socket there -- /run is root:root 755
// in that image, so "stats socket /run/haproxy.sock ..."/"/run/admin.sock"
// fails HAProxy startup outright. /tmp is writable regardless of the
// container's uid, so both generated config files (haproxy.cfg,
// haproxy_check.cfg) must use a /tmp path for their local admin socket
// instead.
func TestOpenSVCHaproxyModulesetUsesNonRootSafeSockets(t *testing.T) {
	data, err := EmbededDbModuleFS.ReadFile("opensvc/moduleset_mariadb.svc.mrm.proxy.json")
	if err != nil {
		t.Fatalf("could not read embedded moduleset_mariadb.svc.mrm.proxy.json: %s", err)
	}
	content := string(data)

	for _, forbidden := range []string{"/run/haproxy.sock", "/run/admin.sock"} {
		if strings.Contains(content, forbidden) {
			t.Errorf("moduleset_mariadb.svc.mrm.proxy.json contains %q -- a non-root HAProxy container can't create a socket under root-owned /run, use a /tmp path instead", forbidden)
		}
	}

	for _, want := range []string{"stats socket /tmp/haproxy.sock", "stats socket /tmp/admin.sock"} {
		if !strings.Contains(content, want) {
			t.Errorf("moduleset_mariadb.svc.mrm.proxy.json does not contain %q -- expected non-root-safe stats socket path", want)
		}
	}
}

// TestOpenSVCProxyModulesetCheckScriptsAndStandbyStatsSocket guards against
// two regressions in the embedded moduleset (opensvc/moduleset_mariadb.svc.mrm.proxy.json)
// that only surfaced under live haproxy-mode=standby testing:
//
//   - proxy_cnf_checkmaster/proxy_cnf_checkslave must have "# %%ENV:GENLINE%%"
//     immediately after their "#!/bin/bash" shebang, opting them out of
//     WriteProxyConfigFile's (cluster/configurator/configurator.go)
//     header-prepend. Without it, the generated "# Generated by ..." header
//     lands before the shebang and the kernel refuses to exec the script
//     ("Exec format error"). The shebang is bash, not plain sh, because the
//     scripts use bash's /dev/tcp -- see
//     TestOpenSVCProxyModulesetCheckScriptsFallBackToDevTcp for why.
//   - proxy_cnf_haproxy (haproxy_check.cfg, haproxy-mode=standby) must bind a
//     TCP stats socket, not just the local /tmp/admin.sock one, or
//     HaproxyProxy.Refresh()'s ApiCmd("show stat") (cluster/prx_haproxy.go)
//     can never reach it and the proxy is permanently reported Failed.
func TestOpenSVCProxyModulesetCheckScriptsAndStandbyStatsSocket(t *testing.T) {
	data, err := EmbededDbModuleFS.ReadFile("opensvc/moduleset_mariadb.svc.mrm.proxy.json")
	if err != nil {
		t.Fatalf("could not read embedded moduleset_mariadb.svc.mrm.proxy.json: %s", err)
	}
	content := string(data)

	shebangThenGenline := "#!/bin/bash\\\\n# %%ENV:GENLINE%%\\\\n"
	if got := strings.Count(content, shebangThenGenline); got != 2 {
		t.Errorf("moduleset_mariadb.svc.mrm.proxy.json contains %q %d times, want 2 (proxy_cnf_checkmaster and proxy_cnf_checkslave) -- without it the generated header lands before the shebang and the script fails to exec", shebangThenGenline, got)
	}

	tcpStatsSocket := "stats socket %%ENV:SERVER_IP%%:%%ENV:SVC_CONF_ENV_PORT_ADMIN%% level admin expose-fd listeners"
	if got := strings.Count(content, tcpStatsSocket); got != 2 {
		t.Errorf("moduleset_mariadb.svc.mrm.proxy.json contains %q %d times, want 2 (proxy_cnf_haproxy_runtime_api and proxy_cnf_haproxy) -- without it in proxy_cnf_haproxy, Refresh()'s runtime-API dial can never succeed in haproxy-mode=standby", tcpStatsSocket, got)
	}
}

// TestOpenSVCProxyModulesetCheckScriptsFallBackToDevTcp guards against
// checkmaster/checkslave regressing to an unconditional "wget" call. A live
// incident showed wget isn't present in the official haproxy:3.4 Docker
// image (Debian 13/trixie, no wget/curl/nc/busybox at all) -- every
// external-check then fails with "command not found" (exit 127) for every
// server uniformly, reported by HAProxy as check_status=PROCERR regardless
// of actual replication state. The scripts must probe for wget first (still
// the simplest, most portable path when it's actually there) and only fall
// back to bash's /dev/tcp -- which needs no external binary at all -- when
// it's missing.
func TestOpenSVCProxyModulesetCheckScriptsFallBackToDevTcp(t *testing.T) {
	data, err := EmbededDbModuleFS.ReadFile("opensvc/moduleset_mariadb.svc.mrm.proxy.json")
	if err != nil {
		t.Fatalf("could not read embedded moduleset_mariadb.svc.mrm.proxy.json: %s", err)
	}
	content := string(data)

	wgetProbe := "if command -v wget >/dev/null 2>&1"
	if got := strings.Count(content, wgetProbe); got != 2 {
		t.Errorf("moduleset_mariadb.svc.mrm.proxy.json contains %q %d times, want 2 (proxy_cnf_checkmaster and proxy_cnf_checkslave) -- wget must still be tried first when it's available, with /dev/tcp only as the fallback", wgetProbe, got)
	}

	for _, statusPath := range []string{"master-status", "slave-status"} {
		checkWget := "wget -O - -q http://%%ENV:SVC_CONF_ENV_MRM_API_ADDR%%/clusters/%%ENV:SVC_CONF_ENV_MRM_CLUSTER_NAME%%/servers/$3/$4/" + statusPath
		if !strings.Contains(content, checkWget) {
			t.Errorf("moduleset_mariadb.svc.mrm.proxy.json does not contain %q -- the wget path must still be present as the primary check mechanism", checkWget)
		}
	}

	devTCP := "exec 3<>/dev/tcp/$HOST/$PORT || exit 1"
	if got := strings.Count(content, devTCP); got != 2 {
		t.Errorf("moduleset_mariadb.svc.mrm.proxy.json contains %q %d times, want 2 (proxy_cnf_checkmaster and proxy_cnf_checkslave)", devTCP, got)
	}
}

// TestOpenSVCHaproxyModulesetChecksAllowForkUnderThreads guards against a
// regression where proxy_cnf_haproxy (haproxy_check.cfg, haproxy-mode=
// standby) declares "option external-check" for checkmaster/checkslave but
// omits "insecure-fork-wanted" in its global section. HAProxy's nbthread
// defaults to the host's CPU count (32 in a live incident this guards
// against), and a multi-threaded worker refuses to fork the external-check
// subprocess without this directive -- every server then reports
// check_status=SOCKERR / "Resource temporarily unavailable" (EAGAIN) rather
// than PROCOK/PROCERR, so nothing ever actually excludes a broken replica
// from the write group despite the check being configured correctly
// otherwise.
func TestOpenSVCHaproxyModulesetChecksAllowForkUnderThreads(t *testing.T) {
	data, err := EmbededDbModuleFS.ReadFile("opensvc/moduleset_mariadb.svc.mrm.proxy.json")
	if err != nil {
		t.Fatalf("could not read embedded moduleset_mariadb.svc.mrm.proxy.json: %s", err)
	}
	content := string(data)

	insecureForkWanted := "external-check\\\\n insecure-fork-wanted\\\\n"
	if got := strings.Count(content, insecureForkWanted); got != 1 {
		t.Errorf("moduleset_mariadb.svc.mrm.proxy.json contains %q %d times, want 1 (proxy_cnf_haproxy's global section, right after \"external-check\") -- without it, a multi-threaded HAProxy worker can't fork checkmaster/checkslave and every check fails with SOCKERR", insecureForkWanted, got)
	}
}
