// replication-manager - Replication Manager Monitoring and CLI for MariaDB and MySQL
// Copyright 2017-2021 SIGNAL18 CLOUD SAS
// Authors: Guillaume Lefranc <guillaume@signal18.io>
//          Stephane Varoqui  <svaroqui@gmail.com>
// This source code is licensed under the GNU General Public License, version 3.

package share

import (
	"strings"
	"testing"
)

// TestOpenSVCHaproxyModulesetUsesNonRootSafeSockets guards against the
// embedded OpenSVC HAProxy templates (opensvc/moduleset_mariadb.svc.mrm.proxy.json,
// var_name "proxy_cnf_haproxy" / "proxy_cnf_haproxy_runtime_api") regressing
// to a stats socket path under /run. A non-root HAProxy container (e.g.
// haproxy:3.4, uid 99) can't create a socket there -- /run is root:root 755
// in that image, so "stats socket /run/haproxy.sock ..."/"/run/admin.sock"
// fails HAProxy startup outright. /tmp is writable regardless of the
// container's uid, so both generated config files (haproxy.cfg,
// haproxy_check.cfg) must use a /tmp path for their local admin socket
// instead.
func TestOpenSVCHaproxyModulesetUsesNonRootSafeSockets(t *testing.T) {
	data, err := EmbededDbModuleFS.ReadFile("opensvc/moduleset_mariadb.svc.mrm.proxy.json")
	if err != nil {
		t.Fatalf("could not read embedded moduleset_mariadb.svc.mrm.proxy.json: %s", err)
	}
	content := string(data)

	for _, forbidden := range []string{"/run/haproxy.sock", "/run/admin.sock"} {
		if strings.Contains(content, forbidden) {
			t.Errorf("moduleset_mariadb.svc.mrm.proxy.json contains %q -- a non-root HAProxy container can't create a socket under root-owned /run, use a /tmp path instead", forbidden)
		}
	}

	for _, want := range []string{"stats socket /tmp/haproxy.sock", "stats socket /tmp/admin.sock"} {
		if !strings.Contains(content, want) {
			t.Errorf("moduleset_mariadb.svc.mrm.proxy.json does not contain %q -- expected non-root-safe stats socket path", want)
		}
	}
}

// TestOpenSVCProxyModulesetCheckScriptsAndStandbyStatsSocket guards against
// two regressions in the embedded moduleset (opensvc/moduleset_mariadb.svc.mrm.proxy.json)
// that only surfaced under live haproxy-mode=standby testing:
//
//   - proxy_cnf_checkmaster/proxy_cnf_checkslave must have "# %%ENV:GENLINE%%"
//     immediately after their "#!/bin/sh" shebang, opting them out of
//     WriteProxyConfigFile's (cluster/configurator/configurator.go)
//     header-prepend. Without it, the generated "# Generated by ..." header
//     lands before the shebang and the kernel refuses to exec the script
//     ("Exec format error"). The shebang is deliberately plain sh, not
//     bash, even though the fallback path below needs bash -- see
//     TestOpenSVCProxyModulesetCheckScriptsFallBackToDevTcp for why.
//   - proxy_cnf_haproxy (haproxy_check.cfg, haproxy-mode=externalcheck) must
//     bind a TCP stats socket, not just the local /tmp/admin.sock one, or
//     HaproxyProxy.Refresh()'s ApiCmd("show stat") (cluster/prx_haproxy.go)
//     can never reach it and the proxy is permanently reported Failed.
func TestOpenSVCProxyModulesetCheckScriptsAndStandbyStatsSocket(t *testing.T) {
	data, err := EmbededDbModuleFS.ReadFile("opensvc/moduleset_mariadb.svc.mrm.proxy.json")
	if err != nil {
		t.Fatalf("could not read embedded moduleset_mariadb.svc.mrm.proxy.json: %s", err)
	}
	content := string(data)

	shebangThenGenline := "#!/bin/sh\\\\n# %%ENV:GENLINE%%\\\\n"
	if got := strings.Count(content, shebangThenGenline); got != 2 {
		t.Errorf("moduleset_mariadb.svc.mrm.proxy.json contains %q %d times, want 2 (proxy_cnf_checkmaster and proxy_cnf_checkslave) -- without it the generated header lands before the shebang and the script fails to exec", shebangThenGenline, got)
	}

	tcpStatsSocket := "stats socket %%ENV:SERVER_IP%%:%%ENV:SVC_CONF_ENV_PORT_ADMIN%% level admin expose-fd listeners"
	if got := strings.Count(content, tcpStatsSocket); got != 2 {
		t.Errorf("moduleset_mariadb.svc.mrm.proxy.json contains %q %d times, want 2 (proxy_cnf_haproxy_runtime_api and proxy_cnf_haproxy) -- without it in proxy_cnf_haproxy, Refresh()'s runtime-API dial can never succeed in haproxy-mode=externalcheck", tcpStatsSocket, got)
	}
}

// TestOpenSVCProxyModulesetCheckScriptsFallBackToDevTcp guards against
// checkmaster/checkslave regressing to an unconditional "wget" call, against
// the fallback regressing to a bash shebang, and against bug #6's fixed
// checkslave target URL regressing back from reader-status to slave-status.
// Two live incidents drove this, on opposite kinds of images:
//   - wget isn't present in the official haproxy:3.4 Docker image (Debian
//     13/trixie, no wget/curl/nc/busybox at all) -- every external-check
//     then fails with "command not found" (exit 127) for every server
//     uniformly, reported by HAProxy as check_status=PROCERR regardless of
//     actual replication state.
//   - bash isn't present in haproxytech/haproxy-alpine (Alpine Linux) --
//     confirmed live via `kubectl exec`, `which bash` empty -- even though
//     that image *does* have wget. A "#!/bin/bash" shebang would fail to
//     exec at all there, a strictly worse failure than the wget gap it
//     would be fixing, and would do so on an image that never needed the
//     fallback in the first place.
//
// So the shebang stays plain "#!/bin/sh" (portable everywhere), wget is
// tried first (the simplest path, and the only one Alpine ever needs), and
// only when wget is missing does the script explicitly invoke `bash -c
// '...'` for /dev/tcp -- never relying on bash being the interpreter itself.
func TestOpenSVCProxyModulesetCheckScriptsFallBackToDevTcp(t *testing.T) {
	data, err := EmbededDbModuleFS.ReadFile("opensvc/moduleset_mariadb.svc.mrm.proxy.json")
	if err != nil {
		t.Fatalf("could not read embedded moduleset_mariadb.svc.mrm.proxy.json: %s", err)
	}
	content := string(data)

	wgetProbe := "if command -v wget >/dev/null 2>&1"
	if got := strings.Count(content, wgetProbe); got != 2 {
		t.Errorf("moduleset_mariadb.svc.mrm.proxy.json contains %q %d times, want 2 (proxy_cnf_checkmaster and proxy_cnf_checkslave) -- wget must still be tried first when it's available, with /dev/tcp only as the fallback", wgetProbe, got)
	}

	bashProbe := "elif command -v bash >/dev/null 2>&1"
	if got := strings.Count(content, bashProbe); got != 2 {
		t.Errorf("moduleset_mariadb.svc.mrm.proxy.json contains %q %d times, want 2 (proxy_cnf_checkmaster and proxy_cnf_checkslave) -- the /dev/tcp fallback must only run when bash is actually confirmed present, never assumed via the shebang", bashProbe, got)
	}

	if !strings.Contains(content, "wget -O - -q ") {
		t.Errorf("moduleset_mariadb.svc.mrm.proxy.json does not contain a %q call -- wget must still be tried as the primary check mechanism", "wget -O - -q ")
	}
	for _, want := range []struct {
		path string
		what string
	}{
		{path: "master-status", what: "checkmaster must keep polling master-status"},
		{path: "reader-status", what: "checkslave must poll reader-status after reprovisioning onto bug #6's fix"},
	} {
		urlPath := "%%ENV:SVC_CONF_ENV_MRM_API_ADDR%%/clusters/%%ENV:SVC_CONF_ENV_MRM_CLUSTER_NAME%%/servers/$3/$4/" + want.path
		if !strings.Contains(content, urlPath) {
			t.Errorf("moduleset_mariadb.svc.mrm.proxy.json does not contain %q -- %s", urlPath, want.what)
		}
	}

	devTCP := "exec 3<>/dev/tcp/$HOST/$PORT || exit 1"
	if got := strings.Count(content, devTCP); got != 2 {
		t.Errorf("moduleset_mariadb.svc.mrm.proxy.json contains %q %d times, want 2 (proxy_cnf_checkmaster and proxy_cnf_checkslave)", devTCP, got)
	}
}

// TestOpenSVCHaproxyModulesetChecksAllowForkUnderThreads guards against a
// regression where proxy_cnf_haproxy (haproxy_check.cfg, haproxy-mode=
// standby) declares "option external-check" for checkmaster/checkslave but
// omits "insecure-fork-wanted" in its global section. HAProxy's nbthread
// defaults to the host's CPU count (32 in a live incident this guards
// against), and a multi-threaded worker refuses to fork the external-check
// subprocess without this directive -- every server then reports
// check_status=SOCKERR / "Resource temporarily unavailable" (EAGAIN) rather
// than PROCOK/PROCERR, so nothing ever actually excludes a broken replica
// from the write group despite the check being configured correctly
// otherwise.
func TestOpenSVCHaproxyModulesetChecksAllowForkUnderThreads(t *testing.T) {
	data, err := EmbededDbModuleFS.ReadFile("opensvc/moduleset_mariadb.svc.mrm.proxy.json")
	if err != nil {
		t.Fatalf("could not read embedded moduleset_mariadb.svc.mrm.proxy.json: %s", err)
	}
	content := string(data)

	insecureForkWanted := "external-check\\\\n insecure-fork-wanted\\\\n"
	if got := strings.Count(content, insecureForkWanted); got != 1 {
		t.Errorf("moduleset_mariadb.svc.mrm.proxy.json contains %q %d times, want 1 (proxy_cnf_haproxy's global section, right after \"external-check\") -- without it, a multi-threaded HAProxy worker can't fork checkmaster/checkslave and every check fails with SOCKERR", insecureForkWanted, got)
	}
}

// TestOpenSVCHaproxyModulesetStandbyBackendsUseConfiguredNames guards
// against proxy_cnf_haproxy (haproxy_check.cfg, haproxy-mode=standby)
// hardcoding its frontend/backend names as literal "service_write"/
// "service_read" instead of the %%ENV:SERVERS_HAPROXY_WRITE_BACKEND%%/
// %%ENV:SERVERS_HAPROXY_READ_BACKEND%% placeholders (cluster/prx_get.go),
// which resolve to cluster.Conf.HaproxyAPIWriteBackend/HaproxyAPIReadBackend.
// proxy_cnf_haproxy_runtime_api already uses these placeholders; standby
// silently ignoring a custom backend name is the same class of drift this
// whole file's earlier regressions came from -- Refresh() (cluster/
// prx_haproxy.go) matches "show stat" rows against the *configured* backend
// name, so a mismatch here leaves the dashboard's write/read groups
// permanently empty even though HAProxy itself is behaving correctly.
func TestOpenSVCHaproxyModulesetStandbyBackendsUseConfiguredNames(t *testing.T) {
	data, err := EmbededDbModuleFS.ReadFile("opensvc/moduleset_mariadb.svc.mrm.proxy.json")
	if err != nil {
		t.Fatalf("could not read embedded moduleset_mariadb.svc.mrm.proxy.json: %s", err)
	}
	content := string(data)

	for _, hardcoded := range []string{"backend service_write", "backend service_read", "default_backend service_write", "default_backend service_read"} {
		if strings.Contains(content, hardcoded) {
			t.Errorf("moduleset_mariadb.svc.mrm.proxy.json still contains %q -- proxy_cnf_haproxy must use %%%%ENV:SERVERS_HAPROXY_WRITE_BACKEND%%%%/%%%%ENV:SERVERS_HAPROXY_READ_BACKEND%%%% like proxy_cnf_haproxy_runtime_api does, not a hardcoded name", hardcoded)
		}
	}

	for _, placeholder := range []string{"%%ENV:SERVERS_HAPROXY_WRITE_BACKEND%%", "%%ENV:SERVERS_HAPROXY_READ_BACKEND%%"} {
		// Each placeholder must appear (at least) twice in proxy_cnf_haproxy
		// alone: once in "default_backend ..." and once in "backend ...".
		// proxy_cnf_haproxy_runtime_api also uses both placeholders, so the
		// total across the whole file is (at least) 4 each.
		if got := strings.Count(content, placeholder); got < 4 {
			t.Errorf("moduleset_mariadb.svc.mrm.proxy.json contains %q only %d times, want at least 4 (2 in proxy_cnf_haproxy_runtime_api, 2 in proxy_cnf_haproxy)", placeholder, got)
		}
	}
}
