Cluster_Test_MasterSlaveSlave]
title = "ClusterTestMasterSlaveSlave"
db-servers-hosts = "127.0.0.1:3317,127.0.0.1:3318,127.0.0.1:3319"
db-servers-prefered-master = "127.0.0.1:3317,127.0.0.1:3318"
db-servers-credential = "root:test"
db-servers-connect-timeout = 1

replication-credential = "root:test"

haproxy=true
haproxy-write-port = 3307
haproxy-read-port = 3306

force-slave-no-gtid-mode  = true

[Default]
prov-orchestrator = "local"
db-servers-binary-path= "/usr/local/mysql/bin/"
haproxy-binary-path= "/usr/local/bin/haproxy"
verbose = true
http-server = true
http-bind-address = "0.0.0.0"
